### ISSUE TITLE
Events broken

### ISSUE THREAD

**Issue by mxworm** [coreGreenberet/homematicip-rest-api#101]
Hi, somehow device updates have been broken between the last release and the current dev.
Mainly in home.py the following fix has broken my updates in home-assistant:
```
    def _get_devices(self, json_state):
+        self.devices = [].    <<<<<
        for id_, raw in json_state["devices"].items():
```

I use  self._device.on_update(self._device_changed) but I don't have a dedicated home.get_current_state() in the called _device_changed function.

Bug or feature?

**Comment by coreGreenberet** [comment]
in this case...probably a bug
I guess moving this to get_current_state might be a better place

**Comment by coreGreenberet** [comment]
@mxworm could you try it with commit 6356ab4458a1cf97c1b7cb6534d44d6fd1439dd6

**Comment by mxworm** [comment]
Hi, now I got stopped by 
```
File "setup.py", line 28
    version=versioneer.get_version(),
    ^
SyntaxError: keyword argument repeated

```

**Comment by coreGreenberet** [comment]
please try again

**Comment by mxworm** [comment]
Now it works fine again, thanks!
