### ISSUE TITLE
Async auth token generation functions

### ISSUE THREAD

**Issue by mxworm** [coreGreenberet/homematicip-rest-api#103]
Hi @coreGreenberet and @sander76, I started to implement the config flow of HomeAssistent. This helps users to generate the auth token directly with the web gui. 
I would need your help with the async implementation of the functions to generate the auth token.

**Comment by sander76** [comment]
@mxworm

So that would mean an async implementation of the following file ?

https://github.com/coreGreenberet/homematicip-rest-api/blob/master/hmip_generate_auth_token.py

**Comment by mxworm** [comment]
@sander76 Mainly yes, but the bigger problem (at least for me) is the auth.py module.

**Comment by mxworm** [comment]
The code from hmip_generate_auth_token.py would go into the HomeAssistant config_flow module of homematicip_cloud.

**Comment by sander76** [comment]
@mxworm I am not familiar with the config flow module. Does it require async ?

**Comment by mxworm** [comment]
@sander76 Its an async state machine which guides the user through the different steps e.g enter ID -> press the button on the device and so on.
But your right at least for the moment I could use the threaded version as well, I will try....

**Comment by sander76** [comment]
@mxworm can you point me to your repo so I can have a look?

**Comment by mxworm** [comment]
@sander76 
So far it's working, but it's threaded code without error catching inside async stuff :-|
https://github.com/mxworm/home-assistant/tree/add-homematicip_cloud-config_flow

**Comment by sander76** [comment]
@mxworm It seems to me the config flow does only work with async methods.
Blocking calls (like the init methods used in HomeMaticIP) are not allowed there. So your solution might work, but will most likely break the system in the end.

Are you familiar with discord ? You can go to the developers channel there and ask for some more info on whether my assumptions are indeed correct and how you should proceed...

**Comment by mxworm** [comment]
@sander76 I think we should move to a async implementation :-)
an I started already https://github.com/mxworm/homematicip-rest-api/tree/add-async-auth
