### ISSUE TITLE
async in the import path

### ISSUE THREAD

**Issue by mxworm** [coreGreenberet/homematicip-rest-api#105]
Hi @sander76 , 

The word `async` in the import path e.g. `from homematicip.async.auth import AsyncAuth` seems to work fine if import is global at the begin of a file. But its not working if the import is in a function!

**Comment by mxworm** [comment]
Maybe @sander76 has a answer, I not a python expert at all :-)

**Comment by coreGreenberet** [comment]
I'm closing this one as we are discussion the root problem in #106
