### ISSUE TITLE
Rename the async package.

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#106]
Async becomes a protected keyword when 3.7 is released.

**Comment by coreGreenberet** [comment]
But how should the package be named? async_?

**Comment by sander76** [comment]
@coreGreenberet I was thinking of `aio`.
That is a much used word for packages using asyncio.

**Comment by mxworm** [comment]
@sander76 

```
homeassistant/components/homematicip_cloud/config_flow.py", line 27
    from homematicip.async.auth import AsyncAuth
                         ^
SyntaxError: invalid syntax
```

I copied to `asyncc` : -) and the issue is gone.

**Comment by sander76** [comment]
@mxworm @coreGreenberet Then it seems the `async` keyword already makes things break. I thought we had some time till 3.7 was released..

**Comment by mxworm** [comment]
If you import at the beginning of the file yes, but inside a function not :-)

Vote: aio

**Comment by coreGreenberet** [comment]
Let's settle it with aio.
Should we rename the classes to? E.g AsyncHome to AIOHome?

**Comment by mxworm** [comment]
I would keep them.

**Comment by sander76** [comment]
@coreGreenberet @mxworm Lets keep the class names intact.
Only rename the package.

**Comment by coreGreenberet** [comment]
@mxworm @sander76 
I've merged the PR #107 and modified the missing settings.
could you please verify that everything is working on your end with the current head?

If yes I will tag it to create a new release

**Comment by mxworm** [comment]
Works perfekt! Thanks!

**Comment by coreGreenberet** [comment]
thanks =)
I've also tagged a new version
