### ISSUE TITLE
How do you find out new functions?

### ISSUE THREAD

**Issue by CodeNightWriter** [coreGreenberet/homematicip-rest-api#12]

**Comment by CodeNightWriter** [comment]
Can you explain wow you find them and with what tools? Have you only find POST methods or also websocket connections for realtime measurements. e.g. current power consumption

**Comment by coreGreenberet** [comment]
I'm using an HTTPS Proxy sniffer(Charles=shareware, Fiddler 4=freeware) to read what the APP on Android does when I make specific actions.
The app is using 2 Connections: One via POST to read/write the configuration, the other one is a simple websocket connection for specific events(push notifications). To be honest I didn't look much into the websocket connection, but as far as i've seen it really gets used only for push notifications(alarm, new smartphone added,..) and not real time data like the power consumption or config changes

**Comment by sander76** [comment]
@coreGreenberet Great work! I am going to take a shot at implementing it in HomeAssistant (https://home-assistant.io/) when I find some time.

But hooking into the above: How do you think the update process of sensor values etc is being done then if not with websockets ? Could it be long polling or something ?

**Comment by coreGreenberet** [comment]
It looks like I'm receiving the updates now also for some other devices and not only security, but yeah I thought It was over pulling.
So either I had problems while catching the traffic or they've implemented it later in the cloud (but I guess it was the first)
