### ISSUE TITLE
Ping fails if socket_connection is None

### ISSUE THREAD

**Issue by chbndrhnns** [coreGreenberet/homematicip-rest-api#122]
I am using the HMIP component in [homeassistant](https://home-assistant.io). It permanently logs errors regarding [this line](https://github.com/coreGreenberet/homematicip-rest-api/blob/897229f5bd2622c8cbded0e39892f40a789554a7/homematicip/aio/connection.py#L130).

Is there maybe a check necessary that `socket_connection` is not None before trying to ping?

The error message goes like that:

```
'NoneType' object has no attribute 'ping'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homematicip/aio/connection.py", line 130, in _ws_ping_loop
    pong_waiter = await self.socket_connection.ping()
AttributeError: 'NoneType' object has no attribute 'ping'
```

**Comment by coreGreenberet** [comment]
might be a workaround but I don't think that this is the problem.

When does the error occur?

Are you closing the connection in homeassistant?

**Comment by sander76** [comment]
A NoneType check is not necessary. The exception is caught [here](https://github.com/coreGreenberet/homematicip-rest-api/blob/897229f5bd2622c8cbded0e39892f40a789554a7/homematicip/aio/connection.py#L140)

I am using hass too, but don't see this error. Could there be any other info in the log that might be useful?

You are using the "official" `homematic-cloud` plugin provided by hass ?

**Comment by sander76** [comment]
Let's close this one and continue [here](https://github.com/home-assistant/home-assistant/issues/18017)

**Comment by chbndrhnns** [comment]
Hi there,
since homeassistant 0.81.4, I do no longer see these kind of errors. I am quite sure nothing changed configuration-wise on my side. Despite the error, the HMIP integration was working absolutely fine, though.
I could just re-open the issue if I notice the errors again.
Thanks!
