### ISSUE TITLE
HMIP-PSM: Report voltage and current

### ISSUE THREAD

**Issue by chbndrhnns** [coreGreenberet/homematicip-rest-api#124]
According to the [HMIP docs, section 67.3.7](https://www.eq-3.de/Downloads/eq3/download bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf), the device also reports voltage and current. Is it possible to add these values to the API?

**Comment by coreGreenberet** [comment]
Sadly no =(
the cloud provides us only the currentPowerConsumtion(W) and the energyCounter (kWh). Since the API is talking directly with the cloud we won't get access to these kind of information until the cloud will provide it to us.
