### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Superwutz** [coreGreenberet/homematicip-rest-api#126]
Hi there,

is there any documentation regarding all the different functions, variables and reading?

I am currently trying to read and control my HMIP-WTH-2, HMIP-PSM and HMIP-FAL230-C6 but have no idea how to do anything more than turning the switch on / off ..

**Comment by coreGreenberet** [comment]
sadly not yet =(
the best option would probably be to just look into the code of the device.py

**Comment by coreGreenberet** [comment]
I've started with the documentation in the branch https://github.com/coreGreenberet/homematicip-rest-api/tree/documentation. As soon as it has "something" in it I will merge it to the master branch.

The doc can currently be found under https://homematicip-rest-api.readthedocs.io/en/documentation/
