### ISSUE TITLE
Missing HMIP Components

### ISSUE THREAD

**Issue by ScooterisT5** [coreGreenberet/homematicip-rest-api#133]
Hello,
i would add a few other missing components:
HmIP-SBI - PRESENCE_DETECTOR_INDOOR
HmIP-WRC6 - PUSH_BUTTON_6
HmIP-RC8 - REMOTE_CONTROL_8
HmIP-KRC4 - KEY_REMOTE_CONTROL_4
HmIP-BROLL - SHUTTER_PROFILE
these show up in the home-assistant.log, with missing classes
HmIP-BSM doesn't shows up at all
HmIP-FSM doesn't shows up at all
HmIP-SRH doesn't show if it is tilt

i don`t have developer skills, but an advanced user skill :-)

How can i support development ?

**Comment by coreGreenberet** [comment]
Please send me an (anonymized) configuration -> https://github.com/coreGreenberet/homematicip-rest-api/issues/114
Since you are using home-assistant you might have to install the library itself on the computer and generate a new token.
Just follor the "Installation" & "Usage" sections of the readme.

**Comment by homeassistant18** [comment]
Ich bin begeistert, dass HomeAssistant zusammen mit Homematic Ip AccessPoint funktioniert. Das Problem ist, dass ich ein Image von HomeAssistant genommen hab und da das System schon auf HASSIO läuft. Der Befehl hmip_cli.py --dump-configuration --anonymize zeigt mir nichts an und ich bekomme einen Fehler. Ich hab fast alle Homematic IP Geräte im Haus eingebaut und bei mir fehlen auch einige. Wenn Sie genau sagen, was ich bei HASSIO eingeben soll, damit Sie es weiterentwickeln können, sagen Sie bitte Bescheid. Homematic AccessPoint Adapter wurde schon bei HASSIO vorinstalliert. Ich werde sehr dankbar wenn Sie eine Schritt für Schritt Anleitung für uns machen. Und nochmal großen Respekt für Ihre Entwicklung.

**Comment by ScooterisT5** [comment]
i am very sorry, but i don't know how to run hmip_cli.py --dump-configuration --anonymize
and i cant find a readme about.
Can you please explain, what i need to do. Step-by-step.
so i can provide requested config

**Comment by t0bse** [comment]
there is another "new" magnetic door sensor: HmIP-SWDM

**Comment by sander76** [comment]
@t0bse @ScooterisT5 @homeassistant18 This library is used on the background by HomeAssistant. But anything missing in homeassistant should not be reported here as @coreGreenberet is not involved in HomeAssistant.
Most of the HomeMatic integration is done by @mxworm and me.
So if you would like to have a device implemented in HomeAssistant I suggest doing the following:

- Make an issue in the HomeAsisstant github repo requestion for the implementation.
- Make an issue per device. Don't provide lists as it makes referencing very difficult.
- Also be aware there are two homematic components available: HomematicIP cloud which uses this libary and "just" HomeMatic (for ccu2, ccu3 etc). Make sure when you make a request to mention the proper platform in the title. This makes it easy to search for open HomeMatic-cloud requests/issues.

Also for managing expectations: We're doing this in our spare time. If you make a request it doesn't mean it will be implemented. Especially as we might not own the device ourselves which makes implementation more difficult. It could however be that another person will pick up the request and implement the device. That's the beauty of Open Source !

All the best !

Sander

**Comment by coreGreenberet** [comment]
I think I've implemented all missing devices. Please create a new issue if there is still a device missing.

**Comment by TobiasKarge** [comment]
What needs to be done so that the BROLL is also integrated.

**Comment by mxworm** [comment]
Hi @TobiasKarge and @sander76,

I don't test the device myself, can you checkout this branch and test if its working properly?
https://github.com/mxworm/home-assistant/tree/homematicip_cloud-cover_broll_froll

Thanks Mattias

**Comment by anrada73** [comment]
Thanks for your help, we are new to hass.io. How to implement what you did to test? hass.io is different from raspberry.
