### ISSUE TITLE
Boost function?

### ISSUE THREAD

**Issue by t0bse** [coreGreenberet/homematicip-rest-api#134]
Is it possible to integrate the boost function for the HMIP-eTRV (Heating thermostate)?
Otherwise i have to push my heater to 30 degrees all the time :)

**Comment by coreGreenberet** [comment]
It's already implemented, but you have to "boost" the heating group and not the device.

**Comment by t0bse** [comment]
> It's already implemented, but you have to "boost" the heating group and not the device.

thank you for your quick answer! can you give me an example? i just want to boost one heater

**Comment by t0bse** [comment]
are you sure this is working in hassio? sorry for my newbie questions :)

**Comment by coreGreenberet** [comment]
Sorry I'm not the developer of the hassio module. I don't know if this is implemented there or not.

**Comment by t0bse** [comment]
> Sorry I'm not the developer of the hassio module. I don't know if this is implemented there or not.

okay sorry, so i will ask @hass.io :)
