### ISSUE TITLE
Set away mode

### ISSUE THREAD

**Issue by chbndrhnns** [coreGreenberet/homematicip-rest-api#136]
Would it be possible to configure the away mode from your client, as well? The app requires a date and time in the future that marks the end of the away mode.

**Comment by coreGreenberet** [comment]
do you mean in the hmip_cli.py? the cli interface supports this already with a duration parameter in "minutes". The API itself supports it with the Home.activate_absence_with_period and Home.activate_vacation methods

**Comment by chbndrhnns** [comment]
Exactly what I was looking for.
