### ISSUE TITLE
AIO Devices: Wrong Inheritance Order?

### ISSUE THREAD

**Issue by coreGreenberet** [coreGreenberet/homematicip-rest-api#139]
At the moment all AIO Devices are using the order "non aio base", "base aio device" for inheritance.
e.g.
```python
class AsyncBrandSwitchMeasuring(BrandSwitchMeasuring, AsyncSwitch):
    """ HMIP-BSM (Brand Switch and Meter) """
```
this might result in an error on calling in this case the AsyncSwitch functions ( turn_on, turn_off, ... )

Simple Console Test:
```python
class A():
    def test(self):
        print("A")
class B():
    def test(self):
        print("B")
class C(A,B):
    pass
c=C()
c.test() #Output: A
```
@sander76 since you've done most of the aio module: How do you think we should proceed here?

**Comment by sander76** [comment]
@coreGreenberet Inheritance order is correct. Your example assumes class C does not have any methods. My async class (which would represent class C in your example) has the methods implemented as async that need to be overridden from the base class.

If I remember correctly my choice for inheriting from two classes was because I didn't want to propose a complete restructure of your library which was required if I wanted a more straightforward async implementation.

But at this moment I don't see any reason to change this. Maybe in the future... Or if you're up to the challenge ;-)

**Comment by sander76** [comment]
@coreGreenberet Doing some extra tests will never hurt! I'm not able to dig into this, and it's been a while since I did this but look here :

https://stackoverflow.com/questions/1848474/method-resolution-order-mro-in-new-style-classes#1848647

To see why it does work. Unless I made a mistake!

**Comment by sander76** [comment]
@coreGreenberet in any way, please let me know if you're going to change things. Homeassistant uses the async part of your library. And as you might have noticed: there are quite some users of home assistant..

**Comment by sander76** [comment]
@coreGreenberet Did you manage to do any testing?

**Comment by coreGreenberet** [comment]
I've just tried it now. But it looks like you can't user super() on all functions.
I had to change AsyncSwitch to this:
```python
...
    async def turn_on(self,channelIndex=1):
        _LOGGER.debug("Async switch turn_on")
        return await self.set_switch_state(True,channelIndex)

    async def turn_off(self,channelIndex=1):
        _LOGGER.debug("Async switch turn_off")
        return await self.set_switch_state(False,channelIndex)
...
```

otherwise I got an exception that coroutine isn't iterateable

**Comment by sander76** [comment]
@coreGreenberet you're now implementing an extra function inside the async wrapper. I don't really see the point.

How are you testing? What does the test code look like ?

The way it was definitely works. Please, please don't just change the work I've done

**Comment by sander76** [comment]
@coreGreenberet the aio part of the library is being used intensively already. If it wouldn't have worked we would have known much earlier already

**Comment by coreGreenberet** [comment]
Depends...are you using the set_switch_state or the turn_off/on functions in HASS.IO?
Well it's not "really" an extra function. The functions were there already, but you are calling super().turn_on which will just call self.set_switch_state

test code is in tests/aio_tests/test_async_device.py

**Comment by coreGreenberet** [comment]
@sander76 okay thanks. Anyway my changes shouldn't break anything as it does basically the same as before.

**Comment by sander76** [comment]
@coreGreenberet The problems started with the following commit:

https://github.com/coreGreenberet/homematicip-rest-api/commit/566146dc75a44084ee870aaf7f232f834e02ca49

Here the `set_switch_state` in the async wrapper got implemented. This breaks my original implementation as the code now wants to call the coroutine as a normal method call. Which is not allowed. This explains the error you're seeing. Your solution is now to call the async `set_switch_state` directly from the async turn on/off methods.

This is where my confusion comes from: I wasn't aware you implemented the async `set_switch_state` method while you were telling me my code was wrong. But it only went wrong the moment the async `set_switch_state` method got implemented.

I guess the way you fixed it is more consistent with your original implementation: Both turn_on/off and switch state are public methods. So they should be properly implemented in the async version too.

On the other hand it makes sense to me for the `set_switch_state` to become private: It offers no extra functionality over the turn-on/off methods. This way it doesn't need to get implemented in the async wrapper. And this reduces the amount of required code, which is a good thing as it reduces maintenance effort and risk of things going wrong.

**Comment by coreGreenberet** [comment]
ah that makes sense!
Well set_switch_state should stay public. If you are using something like an external trigger with True/False you can just pass it as a variable to set_switch_state. Otherwise you would always have to create something like this
```python
if something:
    device.turn_on()
else:
    device.turn_off()
```
instead of a one liner
```python
device.set_switch_state(something)
```
No worries! I don't plan to abond this library.
