### ISSUE TITLE
Move `hmip_generate_auth_token` inside the library

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#143]
Move the `hmip_generate_auth_token.py` file inside the package.
Create an `entry-points` entry inside `setup.py` to enable invocation from anywhere.
For example look here:

https://github.com/sander76/pv_prompt/blob/master/setup.py

**Comment by coreGreenberet** [comment]
What's the reason for it? At the moment it will put the script in the Installation, so you can just run it from the command-line.

**Comment by sander76** [comment]
Ah.. is it.? I always thought it wasn't included at a pip install from pypi. Oeps my mistake. We can close then...

**Comment by coreGreenberet** [comment]
It's there since Version 0.9 (March 2018)

**Comment by sander76** [comment]
@coreGreenberet I actually knew that 🙄
