### ISSUE TITLE
Add to github page HmIP-eTRV2 and HmIP-eTRV-B

### ISSUE THREAD

**Issue by saepfle** [coreGreenberet/homematicip-rest-api#145]
Hi,

I guess they are supported but not written on your github starting page with supported devices:
- HmIP-eTRV2 and HmIP-eTRV-B

Could you add them - thank you

Regards

Thomas

**Comment by coreGreenberet** [comment]
I've added HmIP-eTRV2, but to be honest I'm not sure if HmIP-eTRV-B will work.
If you own one, could you please post your anonymized configuration?

**Comment by saepfle** [comment]
How to get in contact with you (E-Mai) I could send you some hardware for test purpose.

**Comment by steckenpferd** [comment]
This issue can be closed configuration data for HmIP-eTRV-B can be found here: https://github.com/coreGreenberet/homematicip-rest-api/issues/150
