### ISSUE TITLE
Getting INVALID_REQUEST in hmip_cli.py

### ISSUE THREAD

**Issue by sfrebel** [coreGreenberet/homematicip-rest-api#151]
Hi,

I guess I am doing something wrong and could need some help.

My setup:
I am Using a Raspberry PI using Python 3.5.3 in a virtualenv. I ran the hmip_generate_auth_token.py and it generated a seemingly valid config.ini. I left this file where it generated (e.g. the working directory) and copied it to /etc/homematicip-rest-api/

The issue I am having is that no commands using the hmip_cli.py are working all of them are giving me a INVALID_REQUEST even if I manually add the path to the configuration to the command (`python hmip_cli.py --config_file config.ini --dump-configuration`)

Everything I try results in this error: `homematicip.home - ERROR - Could not get the current configuration. Error: INVALID_REQUEST` additionally the dump-configuration returns `root - ERROR - Could not get the current configuration. Error: INVALID_REQUEST`.

I would be grateful for pointers to what I am doing wrong so I can get using the api.

**Comment by coreGreenberet** [comment]
depending on your OS it might be, that there is python 2.X and 3.5.3 installed
please try to run it with python3 or directly with "hmip_clip.py --dump-configuration"

**Comment by coreGreenberet** [comment]
When you open the HMIP Client, are you still able to see the api client under "clients"? If yes, then delete it.
Please rerun `hmip_generate_auth_token.py`

**Comment by coreGreenberet** [comment]
Do you still have this problem? Would you mind to send me the config.ini?(mail or over the homematic forum as pm) I would like to verify with my environment

**Comment by coreGreenberet** [comment]
I will close this issue as this isn't a problem on the library
