### ISSUE TITLE
Alarm ever activate arm_away never arm_home

### ISSUE THREAD

**Issue by Obicom** [coreGreenberet/homematicip-rest-api#154]
Hi coreGreenberet,

I have the issue that the alarmcontrol panel activates everytime arm_way equal if I switch arm_home or arm_away. If you switch on arm_home it needs some second (pending) and comes back with swichting both alarmpanel actors (away & home) to "armed_away". in HmIP App it shows every time "Vollschutz aktiv". I checked this with some other German hassio users and they confirmed this issue. Is this something that you could change?

**Comment by coreGreenberet** [comment]
Sorry no, that's in hassio. The api supports both methods.

**Comment by coreGreenberet** [comment]
@Obicom https://github.com/home-assistant/home-assistant/pull/20321
