### ISSUE TITLE
Neue Geräte -  HmIP-SMO-A -  HmIP-FCI1

### ISSUE THREAD

**Issue by anrada73** [coreGreenberet/homematicip-rest-api#155]
Hallo, da sind fehlende Geräte:
-  HmIP-SMO-A
-  HmIP-FCI1

MfG

https://gist.github.com/coreGreenberet/16865dae641b8a6e0d07e4090dc20ae2

**Comment by coreGreenberet** [comment]
Thanks,
please use a gist or something similiar in the future. the configs are long texts which will make the comments hard to scroll (especially on mobile devices)

**Comment by coreGreenberet** [comment]
HmIP-SMO-A is already implemented

**Comment by anrada73** [comment]
Ok, danke. Sag welche Geräte brauchst du noch )

**Comment by steckenpferd** [comment]
Hier siehst du im Excel in der ersten Spalte wo kein “x” ist welche Geräte noch fehlen.
https://dl.dropboxusercontent.com/s/nma2rtpafgngy2e/REST-API.vs.ioBroker.HmIP.xlsx
