### ISSUE TITLE
implement HmIP-FDT

### ISSUE THREAD

**Issue by weinbrand** [coreGreenberet/homematicip-rest-api#164]
Hi, please implement the devices mentioned above. Here is the anonymized config.

https://pastebin.com/X5TA51cC

Do you need anyhting else?

**Comment by coreGreenberet** [comment]
it's already implemented. Are you missing something specific?

**Comment by coreGreenberet** [comment]
If the issue is only from home assinstant, then please create an issue there
https://github.com/home-assistant/home-assistant
