### ISSUE TITLE
implement HmIP-SLO

### ISSUE THREAD

**Issue by MarkusJankowski** [coreGreenberet/homematicip-rest-api#166]
Hello,

please implement HMIP-SLO.
Here is my anonymized config: https://pastebin.com/KGjHDARU

Thanks a lot
and BR
Markus

**Comment by coreGreenberet** [comment]
are the average/lowest/highst values from the current day/week/month/total?
can these values be reseted?

**Comment by MarkusJankowski** [comment]
I think these values (average/lowest/highst) are an aggregation over the last X measurements.
As far i could remember the last 6 measurements are used in CCU, but i cannot switch this setting in AP. These values cannot be reseted.

**Comment by coreGreenberet** [comment]
implemented in fc4e5eae943f8f0298a75754bb8750b7cc32e74d.
I've also released a new version.
