### ISSUE TITLE
Api for slatsLevel ?

### ISSUE THREAD

**Issue by jogibear9988** [coreGreenberet/homematicip-rest-api#168]
Do you have the api call to set the slatsLevel?

**Comment by coreGreenberet** [comment]
I think I can grab it, but I'm on a business trip and I don't have access to my private computer.
so it might take a week.

**Comment by steckenpferd** [comment]
Ans news?

**Comment by coreGreenberet** [comment]
```python
    def set_slats_level(self, slatsLevel=0.0):
        data = {"channelIndex": 1, "deviceId": self.id, "slatsLevel": slatsLevel}
        return self._restCall("device/control/setSlatsLevel", json.dumps(data))
```

could you please try this? I think slatsLevel must be between 0.0 and 1.0

**Comment by jogibear9988** [comment]
I‘ve already implemented like this 
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/api/hm-cloud-api.js#L198 but they said it did not work

**Comment by coreGreenberet** [comment]
What did the cloud answer to the call?

**Comment by jogibear9988** [comment]
hmm, don‘t know. 
only a user said it didn‘t work

**Comment by jogibear9988** [comment]
@coreGreenberet do you have any idea abou this: https://forum.iobroker.net/viewtopic.php?f=36&t=21000&p=229845#p229845

**Comment by coreGreenberet** [comment]
"Das von dir ausgewählte Thema existiert nicht."

**Comment by Leonid1462** [comment]
in the app I can change shutterLevel and slatsLevel to any value between 0% and 100%. It works perfectly.
In ioBroker the respective values are not reflecting any status change. (no update)

**Comment by jogibear9988** [comment]
pleasee switch the adapter to silly and post the logs

**Comment by Leonid1462** [comment]
starting position from app screen:  shutterLevel on 100% and slatsLevel on 65%
changed in ioBroker the value for slatsLevel to 1. Shutter moves up and shows in app afterwords shutterLevel = 5% and slatsLevel = 100%.
Log:

hmip.0 | 2019-02-06 21:40:55.058 | info | state change - slatsLevel - id 3014F711A0001397099C4322 - value 1
-- | -- | -- | --
hmip.0 | 2019-02-06 21:40:55.044 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.slatsLevel

then changed the slatsLevel to 0.5.  Results in 50% slatsLevel in the app.
Log:

hmip.0 | 2019-02-06 21:45:20.923 | info | state change - slatsLevel - id 3014F711A0001397099C4322 - value 0.5
-- | -- | -- | --
hmip.0 | 2019-02-06 21:45:20.903 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.slatsLevel

It seems that when ever I change the slatsLevel it moves it correctly but also moves up the shutter to highest position. (not shown in ioBroker)
Same when I change the shutterLevel. As you can see in the latest log I changed shutterLev to 0.8. Shutter moves down to 80% but same time slatsLevel closes to 100%

Log:

hmip.0 | 2019-02-06 21:49:31.723 | info | state change - shutterlevel - id 3014F711A0001397099C4322 - value 0.8
-- | -- | -- | --
hmip.0 | 2019-02-06 21:49:31.702 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.shutterLevel
hmip.0 | 2019-02-06 21:48:48.907 | info | state change - slatsLevel - id 3014F711A0001397099C4322 - value 0.29
hmip.0 | 2019-02-06 21:48:48.889 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.slatsLevel
hmip.0 | 2019-02-06 21:48:17.207 | info | state change - shutterlevel - id 3014F711A0001397099C4322 - value 0.5
hmip.0 | 2019-02-06 21:48:17.189 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.shutterLevel
hmip.0 | 2019-02-06 21:45:20.923 | info | state change - slatsLevel - id 3014F711A0001397099C4322 - value 0.5
hmip.0 | 2019-02-06 21:45:20.903 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.slatsLevel
hmip.0 | 2019-02-06 21:40:55.058 | info | state change - slatsLevel - id 3014F711A0001397099C4322 - value 1
hmip.0 | 2019-02-06 21:40:55.044 | silly | inMem message  hmip.0.* hmip.0.devices.3014F711A0001397099C4322.channels.1.slatsLevel

**Comment by coreGreenberet** [comment]
I think I found the problem.
setSlatsLevel expects a shutterLevel parameter. Since it was missing it was using it as "0" -> move them up

```python
    def set_slats_level(self, slatsLevel=0.0, shutterLevel=None):
		if shutterLevel is None:
			shutterLevel = self.shutterLevel
        data = {"channelIndex": 1, "deviceId": self.id, "slatsLevel": slatsLevel, "shutterLevel": shutterLevel}
        return self._restCall("device/control/setSlatsLevel", json.dumps(data))
```

**Comment by jogibear9988** [comment]
@coreGreenberet does then the shutterlevel command also need a slats level? or is always the slats command used?

and do you know 
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf

**Comment by coreGreenberet** [comment]
The setShutterlevel doesn't have the slats parameter. 

Yes I know that document, but sadly out doesn't reflect the cloud :(

**Comment by jogibear9988** [comment]
@coreGreenberet and that https://media.readthedocs.org/pdf/homematicip-rest-api/latest/homematicip-rest-api.pdf

**Comment by coreGreenberet** [comment]
@jogibear9988 @Leonid1462 does it work now as expected?

**Comment by Leonid1462** [comment]
sorry, but I can‘t test anything at the moment. I‘m not at home the next 8 days

**Comment by coreGreenberet** [comment]
@Leonid1462 any update?

**Comment by steckenpferd** [comment]
Here you find Lenids feedback in the iobroker forum: https://forum.iobroker.net/topic/18872/aufruf-homematic-ip-cloud-access-point-adapter/155

**Comment by Leonid1462** [comment]
My latest findings:  Editing the slatsLevel directly in the objects table of iobroker is meanwhile possible without interfering with the shutterLevel. But, without knowing why, the shutters are not acting correctly. I put there a slatsLevel = 0.3 and the shutter opens the slats complitly (which would normaly mean slatsLevel = 0).  The HmIP App shows afterwards slatsLevel = 30%.  (If I change in the app to 29% or 31% it moves into the correct position)
Then I have introduces script and scene and steared the slatsLevel by this and that works perfectly.  It accepts any slatsLevel between 0 and 1 and moves the shutter into the desired position.
Honestly I don't know where this different behaviour comes from.

**Comment by coreGreenberet** [comment]
When you say Script...so you mean with this python api or something in iobroker?

**Comment by Leonid1462** [comment]
Yes, blockly script in iobroker

**Comment by coreGreenberet** [comment]
okay so basically the function should be alright.
I will close the issue here for now.
