### ISSUE TITLE
Problem to read "on" of a homematic push button

### ISSUE THREAD

**Issue by jogibear9988** [coreGreenberet/homematicip-rest-api#169]
I've a homematic push button, but I've not yet assigned to an actor.

Is it possible to read the state? In the json I read over the websocket "on" is always "null"

**Comment by coreGreenberet** [comment]
Sorry i don't know. The last push button configuration I've received didn't have an "on" value.

**Comment by jogibear9988** [comment]
means I can do nothing with the push buttons via the API?

**Comment by coreGreenberet** [comment]
Sadly not really :( maybe they have changed the event, so that you can see which button got pressed, but you have to check this, because I don't own one to test it myself

**Comment by SukramJ** [comment]
I also tried to figure out how push buttons might work with the API. I am a python newbie, so event handling is quiet unclear and the given example is too short for me, but could be that we get an event where we could read out the effected channel? 
(Just my personal expectation.)

**Comment by SukramJ** [comment]
Do you have a better sample with event handling, so that we can test it against the real buttons?

**Comment by coreGreenberet** [comment]
That's actually what I thought...maybe we are getting only the effected channel on the event, but I think we will get the full one.


You could run hmip_cli.py --list-events with a loglevel of debug

**Comment by jogibear9988** [comment]
problem is, you don‘t get an event from the homematic ip cloud

**Comment by coreGreenberet** [comment]
Well then we can't do anything :(

**Comment by jogibear9988** [comment]
yeah...
If I attach the button to a plugable switch, I get the valuen from the switch, that it is on, but none from the button.
I'm now experimenting with groups

**Comment by jogibear9988** [comment]
@sander76 you could use a button to set holiday mode to a value (a different one for each button). then you could use this to work with

**Comment by coreGreenberet** [comment]
I guess the best option would be to buy a mod-oc8. That way you will have 8 switches/variables to play with.

**Comment by jogibear9988** [comment]
I've 2 push buttons...

**Comment by sander76** [comment]
Holiday mode... Hmmm...

**Comment by coreGreenberet** [comment]
yes but with the mod 8 you can use 2 of them for your buttons (maybe even 4 with the long press thingy).
e.g.
Button 1 press -> switch 1 to on
Button 2 press -> switch 2 to on

in home-assistant/iobroker/.... 

Switch 1 got turned on -> "someone has pressed button 1" -> turn switch 1 off and do action XYZ


Holiday mode would be a bad idea in my opinion. for each button press you will generate messages for each "heating" device (not sure if they are using broadcasts). so you might hit the duty cycle

**Comment by jogibear9988** [comment]
> I guess the best option would be to buy a mod-oc8. That way you will have 8 switches/variables to play with.

before I would do that, I will change to not use the CloudIpAccessPoint and assign the devices directly to rasp PI via a CUL or smth similar

**Comment by coreGreenberet** [comment]
I'm closing this as we can't really do somethin about that.

**Comment by steckenpferd** [comment]
Why not do it like the CCU. Read out which button is direct connected with which device e.g. WRC2 Button 1 - with HmIP-PSM Status “On”. So when you want to trigger the Button for WRC2 thru the cloud l, instead you read the direct connection and trigger (like thru a tunnel) instead the HmIP-PSM to status “On”. 
Would that not work for all this:
Remote Control - 8 buttons (HmIP-RC8)
Wall-mount Remote Control - 2-button (HmIP-WRC2)
Wall-mount Remote Control - 6-button (HmIP-WRC6)
Key Ring Remote Control - 4 buttons (HmIP-KRC4)
Key Ring Remote Control - alarm (HmIP-KRCA)

**Comment by SukramJ** [comment]
This is not the way the CCU works.
In your scenario the PushButton info is not needed, because you have connected switches to read a state.
CCU also works without connected switches.

**Comment by steckenpferd** [comment]
I just tested it with the CCU and Hm-pb-2-wm55 and @Home App. When I trigger thru the app the Hm-pb-2-wm55 battery Taster it doesn’t reacts (normally green light flashes when pressed) but my direct connected light with the Taster goes “on”. So the CCU is triggering instead the light which is direct connected to the Taster - makes sense. Pretty sure here.
I can test the same with Homematic Manager if you want.
