### ISSUE TITLE
Since HA 0.86.x all smoke detectors of HmIP have the state "smoke detected"

### ISSUE THREAD

**Issue by Obicom** [coreGreenberet/homematicip-rest-api#170]
Hi coreGreenberet,

Since home assistant version 0.86.x all smoke detectors of HmIP have the state "smoke detected". For me this is a real security issue. I do not know if it has something to do with your rest api or is a issue in the HA implementation. Could you or @sander76 / @mxworm be so kind to do a deeper look inside? Serveral HmIP/HA users in our German facebook group confirmed the same behavior. So it is not a singel case is a overall issue. Thank you in advance.

**Comment by coreGreenberet** [comment]
Please post home assistant issues in the home assistant repository. 

And this issue is already fixed in the repository, so it should be in the next release.

**Comment by Obicom** [comment]
Thank you for the information @coreGreenberet . I did it also on HA issue list but I saw no progress or response.
