### ISSUE TITLE
Please integrate push action for switches in the API

### ISSUE THREAD

**Issue by Obicom** [coreGreenberet/homematicip-rest-api#173]
Hi coreGreenberet,

lot of users wish the implementation of HmIP push buttons (switches e.g. HmIP-WRC6) in home assistant. mxworm say is not possible in regards of the API (see enclosed screenshot). In the new homematic ip integration in iobroker it was solved, so it could not be impossible. Could you take a look on this topic please? Would be great (e.g. for automation) if we could use the wall switches and remote controls. Thank you in advance. Best regrads, Dirk

![image](https://user-images.githubusercontent.com/25134482/52537751-59547000-2d6a-11e9-9eb3-16c4471ce42d.png)

**Comment by SukramJ** [comment]
Read [this](https://github.com/coreGreenberet/homematicip-rest-api/issues/169)

It is not possible.

**Comment by Obicom** [comment]
I am confused why it is possible with ioBroker but not with HA. Maybe the different developers should exchange there knowledge.

**Comment by SukramJ** [comment]
I don't think it is possible with iobroker. [See](https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/34)

**Comment by coreGreenberet** [comment]
Sadly it's not possible :( eq3 doesn't give us this information
