### ISSUE TITLE
Invert signal state of HMIP-SWDO

### ISSUE THREAD

**Issue by FlavorFx** [coreGreenberet/homematicip-rest-api#176]
The shutter component has a feature to invert the state. "open" means "closed" and "closed" means "open". This feature is assessable by Homematic CCU but not by Homematic IP. Is there is way to get access by rest-api?

**Comment by coreGreenberet** [comment]
Not by the api itself.
It could be implemented though. Could you tell me an example why you needed need it inverted?

**Comment by FlavorFx** [comment]
Well, I have a shutter in my post box at a certain position. When flap opens, the shutter closes. By Homematic CCU it was easy to invert the signal but with HMIP not. eQ3 is not really motivated to make this feature available. 
Only change it in HA is not what I'm looking for. I was hope to find a way to get access to the sensor feature itself.

**Comment by coreGreenberet** [comment]
Sorry :(
