### ISSUE TITLE
homatic no data after a day

### ISSUE THREAD

**Issue by jogibear9988** [coreGreenberet/homematicip-rest-api#178]
hello @coreGreenberet 
is this https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/35
a problem you know? is there a automatic disconnection ?

**Comment by coreGreenberet** [comment]
to be honest I don't know.
@sander76 has implemented a ping loop in the async part of the library. Maybe because of that

**Comment by sander76** [comment]
@jogibear9988 At times connection with the websocket get lost (client side or server side)
It is the client's task to handle this disconnect. Among other the asynio implementation has indeed a ping loop built in. The software will need to handle the exception raised by a failed ping or other disconnect.

Not sure how this is handled in iobroker. Don't know the software.

**Comment by jogibear9988** [comment]
it has nothing to do with iobroker, it‘s only in my adapter!

so i will implement a ping pong
