### ISSUE TITLE
Thermostat compact (HMIP-eTRV-C) does not work

### ISSUE THREAD

**Issue by stefancyliax** [coreGreenberet/homematicip-rest-api#183]
Hey guys

you state that the compact thermostat should work, but it does not. 
HMIP-eTRV-C (Heating-thermostat compact without display not tested, but it should work)

Home Assistant 0.88 shows the following error message:
"There is no class for device 'HEATING_THERMOSTAT_COMPACT' yet"
If there is some part I can help with, tell me.

Thanks

**Comment by steckenpferd** [comment]
Please post your log data - like here described:
https://github.com/coreGreenberet/homematicip-rest-api/issues/150

**Comment by stefancyliax** [comment]
Here you go
https://gist.github.com/stefancyliax/3050994d5d4d2d39400aab53bba0f5bc

**Comment by stefancyliax** [comment]
Great. Thanks!

**Comment by steckenpferd** [comment]
@mxworm can you add it now to Home Assistant
