### ISSUE TITLE
Missing HEATING_FAILURE_ALERT_RULE_GROUP

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#184]
Hi,

i have new issue in my  HA logs:
`There is no class for group 'HEATING_FAILURE_ALERT_RULE_GROUP' yet
`
Might be related by to the latest eQ-3 maintenance on thursday.

Here is my [config](https://gist.github.com/SukramJ/6c521547a075bd2cff92195392765d31).

BR
Markus

**Comment by SukramJ** [comment]
There are also new properties for HeatingGroup:

            "valveSilentModeEnabled": false,
            "valveSilentModeSupported": false,

**Comment by coreGreenberet** [comment]
I've implemented them today eea3fdbb03ab846010006fab6119e3d00bed3af6.
I'm still missing the activate/deactivate functionality. Even though it has an "enabled" parameter it looks like that the app will just create/remove the whole group on enable/disable
