### ISSUE TITLE
Websocket exception handling

### ISSUE THREAD

**Issue by PalatinCoder** [coreGreenberet/homematicip-rest-api#190]
I implemented kind of a "watchdog" script using your library, which *should* run 24/7. This works pretty well, however from time to time the websocket connection is reset:
```
error from callback <bound method Home._ws_on_error of <homematicip.home.Home object at 0x749f4fd0>>: the object must be str, bytes or bytearray, not 'ConnectionResetError'

  File "/home/pi/.local/lib/python3.5/site-packages/websocket/_app.py", line 343, in _callback
    callback(*args)
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/home.py", line 663, in _ws_on_error
    LOGGER.error("Websocket error: %s", bytes2str(message))
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/base/helpers.py", line 49, in bytes2str
    b.__class__.__name__
```
I tried recovering from the ConnectionResetError as well as occasional TimeoutError with try...catch, but this clearly doesn't work, as the exception is not actually thrown but bytes2str has trouble converting it to str.

From https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L103: 

> The 2nd argument is exception object.

`_on_error` will always receive an exception object.
I would suggest at least logging the exception with `LOGGER.exception` and (maybe configurable?) throw the exception, so that scripts using the library can recover from errors in the websocket connection. Or, even better, the lib could directly reestablish the connection on TimeoutError resp. ConnectionResetError.

What do you think?

**Comment by coreGreenberet** [comment]
i guess an optional auto reconnect wouldn't be bad here, but I don't know when I have the time to implement it at the moment =(

**Comment by PalatinCoder** [comment]
I would greatly appreciate that 😄 
In the meantime, please consider #191 , which implements my suggestion on throwing the exception to the outside. Thank you!

**Comment by coreGreenberet** [comment]
#191 is merged
