### ISSUE TITLE
Missing items for HmIP-MIOB

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#195]
Hi @coreGreenberet,

the switches (3680W and 1840W) are missing in the implementation for HmIP-MIOB.

BR
Markus

**Comment by coreGreenberet** [comment]
are you sure? Aren't these in self.functionalChannels[1] and 2?

**Comment by SukramJ** [comment]
Sorry, you are right.

**Comment by SukramJ** [comment]
Next question:
There is no method to control the analog output?

**Comment by SukramJ** [comment]
And there is no value for channel 3 and 4 (GENERIC_INPUT_CHANNEL).
Correct?

**Comment by SukramJ** [comment]
Hi i started a PR home-assistant/home-assistant#22975.

**Comment by coreGreenberet** [comment]
Sadly we don't get the value from the input channel. For the analog output channel...I don't know. Is it possible to control it via the app?

**Comment by SukramJ** [comment]
I can't tell you. I don't have one, but that would be my expectation.
