### ISSUE TITLE
Freeze after SGTIN entered

### ISSUE THREAD

**Issue by Skibbie** [coreGreenberet/homematicip-rest-api#197]
Could you please help to get the auth token generated?
After entering the SGTIN nothing happens anymore.

I'm using piVCCU3 with HmIP-RFUSB - could this be found only by SGTIN or do I have to configure the network / IP-address / anything else???

Adding a timeout or other instructions, would be great. Program couldn't even aborted with STRG+C - had to kill via second console.

**Comment by steckenpferd** [comment]
My friend CCU/pivCCU/RaspberryMatic have no Cloud and not using this API. 
@Jochen this issue should be closed.

**Comment by coreGreenberet** [comment]
As @steckenpferd said. This API is only for cloud connected environments
