### ISSUE TITLE
Please make value "OTAU error count" visible (if possible :) )

### ISSUE THREAD

**Issue by user45876** [coreGreenberet/homematicip-rest-api#199]
After having problems getting Firmware delivered to devices, eq-3 Support gave me this:

000000000000000000000000, [PANIC][groupname][Lichter][Roomname- SWITCHING], HmIP-BSM
DELIVER_FIRMWARE_IMAGE -> 1.12.6 (current version 1.10.12)
**OTAU error count: 166,** RF state: OK, RSSI in: -52, RSSI out: -51, battery OK

Is it possible to get this value "OTAU error count" from the API?

Thanks a lot :)

**Comment by coreGreenberet** [comment]
Sadly we don't see the error count =(

**Comment by user45876** [comment]
Thank you very much. That is indeed sad.
