### ISSUE TITLE
HmIP-BBL Jalousieaktor

### ISSUE THREAD

**Issue by steckenpferd** [coreGreenberet/homematicip-rest-api#202]
Hi,

reichen die Info's aus dem LOG hier aus um den BBL hinzuzufügen:
https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/23

**Comment by coreGreenberet** [comment]
Sollten reichen. Ich dachte eigentlich, dass ich den bereits implementiert habe 🤔

**Comment by 22kW** [comment]
HmIP-BBL wird bei mir auch als nicht unterstützt angezeigt:
https://gist.github.com/22kW/9b0f4064be28c368b96f13417331fc3c
