### ISSUE TITLE
REST API Documentation

### ISSUE THREAD

**Issue by SamDecrock** [coreGreenberet/homematicip-rest-api#204]
Hi,

I like it that you made a Python wrapper for the REST API. But do you also have a document describing the REST API? This way, I can build my own wrapper without going through the whole reverse engineering process again. 

Thanks!
Sam

**Comment by steckenpferd** [comment]
Documentation can be found under https://homematicip-rest-api.readthedocs.io

**Comment by SamDecrock** [comment]
I've already looked on that page. I can only find the documentation regarding the Python code.

I'm looking for something that documents the real RESET API. So documenting API calls like:

```
POST /hmip/auth/connectionRequest
POST /hmip/auth/isRequestAcknowledged
POST /hmip/auth/requestAuthToken
POST /hmip/auth/confirmAuthToken
```

**Comment by coreGreenberet** [comment]
Sadly there is none. The best thing would be to convert my python code.
