### ISSUE TITLE
activateVacation does not work

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#223]
Hi,

i tried to activate Vacation but it didn't work.

Here are some infos:
body: '{"endtime": "2019_08_11 14:00", "temperature": 14.0}'
path: 'https://srv07.homematic.com:6969/hmip/home/heating/activateVacation'
result: <ClientResponse(https://srv07.homematic.com:6969/hmip/home/heating/activateVacation) [400 Bad Request]>
<CIMultiDictProxy('Content-Type': 'application/json', 'Connection': 'close', 'Content-Length': '31')>

Any ideas? What else do you need?
Thanks in advance

BR
Markus

**Comment by SukramJ** [comment]
BTW:
activate_ecomode_with_duration
activate_ecomode_with_period
deactivate_ecomode
deactivate_vacation

work without issue.

**Comment by coreGreenberet** [comment]
should work now

**Comment by SukramJ** [comment]
Hi,
thanks, works now. 
Sorry, I forgot to answer.
Is it possible for you to create a new release this week?

BR
