### ISSUE TITLE
New device HmIP-SCI

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#224]
Hi,

there is a new device in my [config](https://gist.github.com/SukramJ/43b676162d341750d15e2323874eeeaa)
HmIP-SCi:

Please have a look.
BR
Markus

**Comment by coreGreenberet** [comment]
merged with PR #226

**Comment by steckenpferd** [comment]
Kurze Rückfrage dazu: Wurde der Code hinzugefügt ohne dass das Gerät physisch gebraucht wurde - falls ja, könnte man so auch die anderen fehlenden Geräte hinzufügen?

**Comment by SukramJ** [comment]
Das Gerät ist "physisch vorhanden".

**Comment by SukramJ** [comment]
Welche Geräte willst Du denn ohne vorhanden sein hinzufügen?

**Comment by steckenpferd** [comment]
Na alle fehlenden wenn es funktioniert hätte ;-)
