### ISSUE TITLE
HmIP-SWDM does not support sabotage

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#227]
Hi,
HmIP-SWDM does not support sabotage.
I will create a PR this evening and add a test.

BR

**Comment by SukramJ** [comment]
Hi,
do you have any plans for a new release.
Currently HmIP-SWDM fails to be available again after a lost internet connection, and this is the only thing i found that might not have been correct with the current implementation.
HA beta might start tomorrow, but I don't want to push you, because i am not 100% sure that this might be the cause.

BR

**Comment by coreGreenberet** [comment]
Maybe I can create a tag today or tomorrow

**Comment by SukramJ** [comment]
That would be great.

**Comment by coreGreenberet** [comment]
0.10.10 is out
