### ISSUE TITLE
There is no class for device 'REMOTE_CONTROL_8_MODULE' yet

### ISSUE THREAD

**Issue by funkschrauber** [coreGreenberet/homematicip-rest-api#230]
Missing component HmIP-MOD-RC8

**Comment by steckenpferd** [comment]
Hi you need to post the config date - here how tobdobit
https://github.com/coreGreenberet/homematicip-rest-api/issues/150

**Comment by funkschrauber** [comment]
[hmip_funkschrauber.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/3460582/hmip_funkschrauber.txt)
