### ISSUE TITLE
Integrate HMIP-SAM Acceleration Sensor

### ISSUE THREAD

**Issue by FlavorFx** [coreGreenberet/homematicip-rest-api#237]
Please integrate **HMIP-SAN** sensor into the homematicip-rest-api so that I can use it as garage door sensor.

**Comment by coreGreenberet** [comment]
Please post your HMIP configuration. See #114 for details

**Comment by FlavorFx** [comment]
Ok, I posted my HMIP config with gist.

**Comment by coreGreenberet** [comment]
I'm currently working on this. Does the HMIP-SAM have any configurable elements, or will it just alert if it got moved?

**Comment by FlavorFx** [comment]
It does:
1st option is assignment to “vibration and movement” or “pan and tilt”
2nd option is detection angle 0 to 45 degree
3rd option acoustic signal back to origin 
4th option acoustic signal from origin to vertical position
5th option neutral position “vertical” or “horizontal”

Please let me know if you have further question.

**Comment by coreGreenberet** [comment]
in the API there is a method for setting the notificationSoundType with the option for HighToLow or LowToHigh which looks like you could do either of them but not both. The JSON on the other side has both values written in it.
How is it in the app? Can you configure both?

**Comment by FlavorFx** [comment]
Yes, I can. There could be a signal out of origin AND there could be another signal back to origin.

I also attached the snapshots of the remaining configuration screens.

**Comment by coreGreenberet** [comment]
I couldn't see the screenshot here on github, but I think that this should do it.

**Comment by FlavorFx** [comment]
Ok, great. I’ll test it when it’s available in Home Assistant.

**Comment by SukramJ** [comment]
@FlavorFx What would you expect if HmIP-SAM is implemented in HA?

I checked the api and currently there is only on attribute (accelerationSensorTriggered) that could be used for a binary_sensor.
Could you post some more configs with this sensor to get a better understanding of it.
- sensor in horizontal position
- sensor in vertical position
- sensor moving from vertical to horizontal position or vice versa.

Thanks

**Comment by FlavorFx** [comment]
A binary sensor sounds fine for me. 

Here is the entire configuration:

Mode of Acceleration Recognition
* "Vibration and Movement" or „Tilting"

Trigger Tilt Angle
0° to 45°

Acoustic Signal back to Origin 
* No Signal, short Signal, two short Signals long Signal

Acoustic Signal out of Origin
* No Signal, short Signal, two short Signals long Signal

Neutral Position
„Vertical" or „Horizontal"

I’m really looking forward to see this sensor in HA.

Please let me know if you need more information. Thanks in advanced.

**Comment by SukramJ** [comment]
Thanks, i meant the hmip config you posted in #114.

**Comment by SukramJ** [comment]
I start with a binary_sensor that displays accelerationSensorTriggered.
Device_class will be DEVICE_CLASS_MOVING.

Additional values displayed as attributes:
- accelerationSensorNeutralPosition
- accelerationSensorMode
- accelerationSensorSensitivity
- accelerationSensorTriggerAngle
 
I am not sure about the additional attributes, if they give a useful info to support the accelerationSensorTriggered value. 


I don't own a HmIP-SAM, so i am unsure about useful combinations.

**Comment by FlavorFx** [comment]
ok, I created four new gists

on with „sensor in origin“ one with „sensor out of origin“, one with „No movement“ and one with „movement“

<script src="https://gist.github.com/FlavorFx/81a132073629170874d28557bea0506a.js"></script>

<script src="https://gist.github.com/FlavorFx/8edd78ca230d63fd7ace8551dbbd6f08.js"></script>

<script src="https://gist.github.com/FlavorFx/7cde538036e5b875cffaca55d1b2db35.js"></script>

<script src="https://gist.github.com/FlavorFx/4ba494a6f03e40fe6efa1346af635c6c.js"></script>

does this help?

**Comment by SukramJ** [comment]
Thanks a lot.

**Comment by SukramJ** [comment]
The PR is already merged to dev. HmIP-SAM will be available in HA with 0.101.
