### ISSUE TITLE
add scripts to the pip setup

### ISSUE THREAD

**Issue by coreGreenberet** [coreGreenberet/homematicip-rest-api#24]
homematicip_cli and generate_auth_token.py should be added to the pip installation

**Comment by sander76** [comment]
relates to this one:

https://github.com/coreGreenberet/homematicip-rest-api/issues/69

**Comment by coreGreenberet** [comment]
this should be implemented now 15b529a97afffd19a76d61ced4dd8cd0f363ce48

**Comment by sander76** [comment]
@coreGreenberet
Great!
You can try if it works by creating an venv and 'python setup.py install' it and see if it works. You might need to move the script inside the package, but I am not sure.
