### ISSUE TITLE
invalid authorization

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#25]
My first throw at this api is trying to get the `homematicip-cli.py` running.
I generate id and token. Put it in the config.py like so:

```python
ACCESS_POINT = 'f02ae3a8-e9ab'  #with the dashes)
AUTH_TOKEN = '6BB8F04728D79' #long one without dashes
```
When I run the cli:
`homematicip-cli.py --list-devices` it returns with an error:

`2017-06-27 13:48:51,973 - homematicip.home - ERROR - Could not get the current configuration. Error: INVALID_AUTHORIZATION`

It seems to be happening with the method on line 121 `home.get_current_state():`
Can anyone confirm whether this occurring to him too ? Or am I doing something wrong.
BTW. My homematicip app reports 'homematicip-python' has been added as a device. So something has gone correct too !

**Comment by marcsowen** [comment]
Please use "generate_auth_token.py" for generating the AUTH_TOKEN. Also the the ACCESS_POINT id seems to be faulty. For reference, my ACCESS_POINT has 24 characters. My AUTH_TOKEN has 64 characters.

**Comment by sander76** [comment]
@marcsowen 
I did use the generate_auth_token.py. I just didn't put the complete string in the example...
Also from my app I get a notification about a new device being added..

Note: I am running python 3.5.2. 
Not sure if that could be causing the error ?

**Comment by coreGreenberet** [comment]
I've just tried it again myself.  It's working fine.  Try to regenerate the auth token and use it again.

**Comment by sander76** [comment]
@coreGreenberet 
Just retried. No luck.
Could it be the cli example is not correct ?

**Comment by sander76** [comment]
it fails at the following POST request:

addres: 'https://ps2.homematic.com:6969/hmip/home/getCurrentState'

BODY 
```
{
    "id": "32 characters generated long string",
    "clientCharacteristics": {
        "language": "en_US",
        "applicationVersion": "1.0",
        "deviceManufacturer": "none",
        "osType": "Windows",
        "applicationIdentifier": "homematicip-python",
        "apiVersion": "10",
        "osVersion": "10",
        "deviceType": "Computer"
    }
}
```

response is 403.
text: b'{\n  "errorCode" : "INVALID_AUTHORIZATION"\n}'

**Comment by sander76** [comment]
@coreGreenberet 
Just did some more tries. Also on a linux machine. Still the invalid_authorization error.
I am wondering what could be wrong.
I followed your online instructions. On generating the auth token a `homematic ip` device appears in my android app. So that seems to go allright. But on using the cli it returns the error.

What is a bit confusing though is the following:

The token generator returns:
- "Token successfully registered" 
- "Client ID"

The config.py needs to have two parameters defined using the above provided values.
- ACCESS_POINT
- AUTH_TOKEN

And I assume `AUTH_TOKEN` needs the string provided by "Token successfully registered". And `ACCESS_POINT` needs the value from "Client ID". Is that correct ? To make it more explicit I guess a better match in wording could be choosen.

**Comment by sander76** [comment]
Crap !
Not the client id but the hub id should be put in the config.py folder. Sorry man....

**Comment by coreGreenberet** [comment]
No Problem
I've changed the prints in the script. This should make it more clearer now =)
