### ISSUE TITLE
Anonymize won't work on the Silvercrest models

### ISSUE THREAD

**Issue by coreGreenberet** [coreGreenberet/homematicip-rest-api#266]
From #265 
Hi @coreGreenberet, please have a look at the SGTINs from Silvercrest.
They start with 30150377 and are currently not covered by the anonymize function.

@SukramJ 
could you please provide me a full id? Are they the same length? Do they have any special characters?

**Comment by SukramJ** [comment]
I saw it in the output of #265. Same length, no special characters.

**Comment by steckenpferd** [comment]
Just in case you need it
[OUTPUT.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/3866173/OUTPUT.txt)

**Comment by coreGreenberet** [comment]
fixed with pr #267
