### ISSUE TITLE
add HMIP-eTRV-B

### ISSUE THREAD

**Issue by steckenpferd** [coreGreenberet/homematicip-rest-api#270]
Hi,

had a HMIP-eTRV-B and added it to the Access Point.

Here the data so you could check and mark it in the readme as added.

[HMIP-eTRV-B.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/3870492/HMIP-eTRV-B.txt)

**Comment by SukramJ** [comment]
This device cannot be used with Home-Assistant?
Just from reading the spec i see no diffrence to existing TRVs.

**Comment by steckenpferd** [comment]
Im not saying that - im saying is not marked on the readme page of github - therefore here the config

**Comment by SukramJ** [comment]
Fine

**Comment by steckenpferd** [comment]
When nothing is missing in the Rest-API documentation then the device could be marked at the readme and this issue should be closed

**Comment by SukramJ** [comment]
The channels (HEATING_THERMOSTAT_CHANNEL, DEVICE_OPERATIONLOCK) already exists, so there is nothing new for the api docs. Just update the ReadMe.

**Comment by steckenpferd** [comment]
https://github.com/coreGreenberet/homematicip-rest-api/pull/274
