### ISSUE TITLE
Add support for garage door module (HmIP-MOD-TM) (dump attached)

### ISSUE THREAD

**Issue by Swiftnesses** [coreGreenberet/homematicip-rest-api#272]
As per our conversation on the HA community forums, here's the dump...

[hmip-config_0831.json.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/3898392/hmip-config_0831.json.zip)

**Comment by Swiftnesses** [comment]
For reference I found this:
https://github.com/danielperna84/pyhomematic/issues/170

**Comment by steckenpferd** [comment]
@coreGreenberet can this not be added to the REST-API docu? Do you need sth more?

**Comment by coreGreenberet** [comment]
I  think so.
Currently work is a little bit to time consuming. I will look into it as soon as I can.

**Comment by steckenpferd** [comment]
Thank you for the feedback

**Comment by Swiftnesses** [comment]
Thank you so much for this, when can I expect to see support in hass.io?

**Comment by coreGreenberet** [comment]
> 
> 
> Thank you so much for this, when can I expect to see support in hass.io?

the best would be to ask @SukramJ. He is implementing the library on hass.io

**Comment by SukramJ** [comment]
HA 0.104.0 will be release 15.1.2020
You could start testing the beta 8.1.2020
