### ISSUE TITLE
Openhab Integration

### ISSUE THREAD

**Issue by viruz82** [coreGreenberet/homematicip-rest-api#273]
Hallo,

sorry, dass ich hier schreibe, aber ich weiß sonst nicht, wo. Gibt es eine Möglichkeit der Integration in Openhab? Ich finde leider nichts dazu.

**Comment by steckenpferd** [comment]
Nope - da musst du dich an Openhab Stellen wenden - das hier ist nur eine Community Dokumentation der API Schnittstelle

**Comment by viruz82** [comment]
Ok, ich hab's befürchtet. Danke für die Info.

**Comment by steckenpferd** [comment]
Alternative zu Openhab - Home Assistant oder ioBroker - hier wurde die Dokumentation eingebaut
