### ISSUE TITLE
HMIP-BSL LED nicht steuerbar

### ISSUE THREAD

**Issue by GLichtenauer** [coreGreenberet/homematicip-rest-api#275]
Hallo, leider kann man beim HMIP-BSL die 2 LEDs (obere / untere Taste) nicht steuern und die Farbe ändern. Wäre super wenn das noch integriert werden könnte.

VG
Günter

**Comment by coreGreenberet** [comment]
Hallo,
hast du es schon mit Async/BrandSwitchNotificationLightset_rgb_dim_level probiert?

**Comment by SukramJ** [comment]
Die Steuerung der LEDs funktioniert ohne Probleme.

**Comment by GLichtenauer** [comment]
Sorry war die falsche Adresse....
