### ISSUE TITLE
Doesn't working on python 3.5 because of one line using python 3.6 syntax

### ISSUE THREAD

**Issue by saschaabraham** [coreGreenberet/homematicip-rest-api#276]
Hello,
installed the library via 
`pip3 install -U homematicip` on a raspberry pi 3 with debian stretch without any errors..
This distro has python 3.5.3. 

So the line 19 in homematicip-rest-api/homematicip/base/base_connection.py  in the master branch created an error because of the f" formatting from python 3.6.

I have changed the line from 

`return f"HmipWrongHttpStatusError({self.status_code})"`

to

`return "HmipWrongHttpStatusError({0})".format(self.status_code)`

and the whole library worked.

Installing with `pip3 install -U homematicip --pre` complains about missing python 3.6

**Comment by coreGreenberet** [comment]
Sorry but python 3.5 has been abonded.
I didn't replace the existing string replacements yet, but thats on my list.
Python 3.5 came out 4 years ago. Sometimes you have to move forward to use new features =)

**Comment by saschaabraham** [comment]
I was not talking about changing the one line, that produces the error with python 3.5 alone.
The problem was, the installation with pip3 install -U homematicip shows no error, no complaining about python 3.5, but installs a library that needs python 3.6. That is the problem.

Ich habe nicht nur von der einen Codezeile gesprochen, welche den Fehler mit python 3.5 auslöst.
Das Problem ist, dass bei der Installation mit pip3 install -U homematicip kein Fehler bzw. Hinweis wegen python 3.5 kommt, aber die installierte lib dann python 3.6 braucht.

Die eine Zeile im Master zu ändern, sollte ja recht einfach sein...
