### ISSUE TITLE
HmIP-FALMOT-C12 integrieren

### ISSUE THREAD

**Issue by weinbrand** [coreGreenberet/homematicip-rest-api#281]
Bitte Fußbodenheizungsaktor integrieren.

[hmip-config_1B11.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/4006410/hmip-config_1B11.txt)

**Comment by SukramJ** [comment]
There is nothing to add to Home-Assistant for this device. The functionality is made available by the required wall thermostats.

**Comment by thecem** [comment]
You are right, at the moment the functionality is made by the wall thermostats.
But it is relevant to have the valve positions and even the config in HA to get some automations running.
So it is possible to get at least the valve positions into HA?
Thx

**Comment by SukramJ** [comment]
No, there is no valve position in HmIP-API for falmot.

**Comment by thecem** [comment]
So, there is no possibility to get the valve status out of the falmot with hmip-hap ?

**Comment by coreGreenberet** [comment]
@thecem I don't have a falmot at home. If you could provide us a new configuration dump, then we could check it again. Maybe EQ3 has added the missing value in the meantime

**Comment by thecem** [comment]
Attached the dump! thx

[hmip-config_C0D1.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/4560812/hmip-config_C0D1.txt)

**Comment by coreGreenberet** [comment]
sadly still not available =(

**Comment by thecem** [comment]
Ya, I’ll keep an ey on that. Maybe with the next firmware. thx

**Comment by thecem** [comment]
Too bad! Nothing new in dump!
