### ISSUE TITLE
HmIP-PMFS

### ISSUE THREAD

**Issue by bonsaijogi** [coreGreenberet/homematicip-rest-api#282]
Please integrate HmIP-PMFS - Plugable Power Supply Monitoring

[hmip-config_CE6F.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/4006919/hmip-config_CE6F.txt)

**Comment by SukramJ** [comment]
HmIP-PMFS will be available with next HA beta and will be released with 0.104.0.
