### ISSUE TITLE
Implementing of HMIP-WTH-B

### ISSUE THREAD

**Issue by swisschocolate** [coreGreenberet/homematicip-rest-api#286]
Any plans to implement the HMIP-WTH-B Homematic IP Wall Thermostat basic? Would be great!

**Comment by coreGreenberet** [comment]
Sadly I don't have this device at home. Could you provide a configuration example?
see #114 for details

**Comment by swisschocolate** [comment]
https://gist.github.com/swisschocolate/3a174a6c15fa4437122123ce4cf2ee0c

**Comment by swisschocolate** [comment]
Wow! Thanks for this very quick commit! I'm excited!
