### ISSUE TITLE
home.json missing in pypi

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#297]
Hi @coreGreenberet,
with #215 i added the home.json to Manifest.in to add  it to the pypi build.
This works locally when i execute `pip wheel .`, but it is not included in the offical pypi build.
Any idea why?

BR

**Comment by coreGreenberet** [comment]
I've just downloaded the tar.gz from pypi and it is included there.

**Comment by SukramJ** [comment]
tar.gz is source, not the wheel.

**Comment by coreGreenberet** [comment]
> 
> 
> tar.gz is source, not the wheel.

I know, but i was only on my mobile and couldn't check the whl. However I've found the issue. It has to be mentioned in the setup.py

see https://github.com/coreGreenberet/homematicip-rest-api/commit/72500c67679845a958e4ee0ad7fac3e6b7c41ccd
