### ISSUE TITLE
HmIP-MOD-HO

### ISSUE THREAD

**Issue by BramSnoodijk** [coreGreenberet/homematicip-rest-api#304]
"devices": {
        "3014F7110000000000000000": {
            "availableFirmwareVersion": "0.0.0",
            "firmwareVersion": "1.0.14",
            "firmwareVersionInteger": 65550,
            "functionalChannels": {
                "0": {
                    "coProFaulty": false,
                    "coProRestartNeeded": false,
                    "coProUpdateFailure": false,
                    "configPending": false,
                    "deviceId": "3014F7110000000000000000",
                    "deviceOverheated": false,
                    "deviceOverloaded": false,
                    "deviceUndervoltage": false,
                    "dutyCycle": false,
                    "functionalChannelType": "DEVICE_BASE",
                    "groupIndex": 0,
                    "groups": [
                        "00000000-0000-0000-0000-000000000004"
                    ],
                    "index": 0,
                    "label": "",
                    "lowBat": null,
                    "routerModuleEnabled": false,
                    "routerModuleSupported": false,
                    "rssiDeviceValue": -71,
                    "rssiPeerValue": -76,
                    "supportedOptionalFeatures": {
                        "IFeatureDeviceCoProError": false,
                        "IFeatureDeviceCoProRestart": false,
                        "IFeatureDeviceCoProUpdate": false,
                        "IFeatureDeviceOverheated": false,
                        "IFeatureDeviceOverloaded": false,
                        "IFeatureDeviceTemperatureOutOfRange": false,
                        "IFeatureDeviceUndervoltage": false
                    },
                    "temperatureOutOfRange": false,
                    "unreach": false
                },
                "1": {
                    "deviceId": "3014F7110000000000000000",
                    "doorState": "CLOSED",
                    "functionalChannelType": "DOOR_CHANNEL",
                    "groupIndex": 1,
                    "groups": [
                        "00000000-0000-0000-0000-000000000005"
                    ],
                    "index": 1,
                    "label": "",
                    "on": false,
                    "processing": false,
                    "ventilationPositionSupported": true
                }
            },
            "homeId": "00000000-0000-0000-0000-000000000001",
            "id": "3014F7110000000000000000",
            "label": "Garage door",
            "lastStatusUpdate": 1584029477755,
            "liveUpdateState": "LIVE_UPDATE_NOT_SUPPORTED",
            "manufacturerCode": 1,
            "modelId": 399,
            "modelType": "HmIP-MOD-HO",
            "oem": "eQ-3",
            "permanentlyReachable": true,
            "serializedGlobalTradeItemNumber": "3014F7110000000000000000",
            "type": "HOERMANN_DRIVES_MODULE",
            "updateState": "UP_TO_DATE"
        }
    },

**Comment by coreGreenberet** [comment]
Could you please provide me some additional informations?
I'm guessing that you can force the door to open, close, stop and ventilation/partial_open ist that correct?

I can see an "on" value for the door and also that the app has a Switch for it. What exactly can you turn on/off on the door?
