### ISSUE TITLE
403 error on connection to homematic ip cloud

### ISSUE THREAD

**Issue by ahilles107** [coreGreenberet/homematicip-rest-api#306]
In my HomeAsistant logs i have 
```
Error connecting to HomematicIP with HAP 3014F711A00003D709AXXXXX. Retrying in 256 seconds
```

And response with code 403 from homematic ip cloud.

**Comment by coreGreenberet** [comment]
I'ts working fine for me. Did you remove HomeAssistant from the client list?
I would try to reintegrate the access point into HA.

**Comment by ahilles107** [comment]
it started to work again today (on our local HA group many people reported this also). Thanks for checking!

**Comment by steckenpferd** [comment]
I guess the reason was the yesterday’s server update by EQ3
