### ISSUE TITLE
HomeMaticIP - HmIP-FSI16 is missing

### ISSUE THREAD

**Issue by helfm** [coreGreenberet/homematicip-rest-api#310]
Dear developers,

unfortunately I cannot integrate the switching actuator of HomeMaticIP (**HmIP-FSI16**) in the Home Assistant.
According to your description I may ask you on this way to develop an integration or extension of the API interface.
Unfortunately I can't provide the dump requested by you, because I can't select the entry: "homematicip_cloud.dump_hap_config" in the developer tools under Services.
I hope that you can still help me and that an integration of the above mentioned Schlatactor in hassio will be possible.

With thanks in advance
Regards Markus

**Comment by Neisi** [comment]
+1

**Comment by coreGreenberet** [comment]
Sorry I would need the configuration to implement it.

**Comment by helfm** [comment]
Thx for this very fast response.

How i can get this "homematicip_cloud.dump_hap_config" service to my hassio configuration?

regards Markus

**Comment by SukramJ** [comment]
Are you admin in your HA?

**Comment by Neisi** [comment]
> Sorry I would need the configuration to implement it.

Which part of the json file do you need? Here is the device part of HmIP-FSI16:

`       "xxxxxxx": {
            "availableFirmwareVersion": "0.0.0",
            "connectionType": "HMIP_RF",
            "firmwareVersion": "1.16.2",
            "firmwareVersionInteger": 69634,
            "functionalChannels": {
                "0": {
                    "coProFaulty": false,
                    "coProRestartNeeded": false,
                    "coProUpdateFailure": false,
                    "configPending": false,
                    "deviceId": "xxxxxx",
                    "deviceOverheated": false,
                    "deviceOverloaded": false,
                    "devicePowerFailureDetected": false,
                    "deviceUndervoltage": false,
                    "dutyCycle": false,
                    "functionalChannelType": "DEVICE_BASE",
                    "groupIndex": 0,
                    "groups": [
                        "00000000-0000-0000-0000-000000000020"
                    ],
                    "index": 0,
                    "label": "",
                    "lowBat": null,
                    "routerModuleEnabled": false,
                    "routerModuleSupported": false,
                    "rssiDeviceValue": -57,
                    "rssiPeerValue": -54,
                    "supportedOptionalFeatures": {
                        "IFeatureDeviceCoProError": false,
                        "IFeatureDeviceCoProRestart": false,
                        "IFeatureDeviceCoProUpdate": false,
                        "IFeatureDeviceIdentify": false,
                        "IFeatureDeviceOverheated": true,
                        "IFeatureDeviceOverloaded": false,
                        "IFeatureDevicePowerFailure": false,
                        "IFeatureDeviceTemperatureOutOfRange": false,
                        "IFeatureDeviceUndervoltage": false
                    },
                    "temperatureOutOfRange": false,
                    "unreach": false
                },
                "1": {
                    "binaryBehaviorType": "NORMALLY_CLOSE",
                    "deviceId": "xxxx",
                    "functionalChannelType": "MULTI_MODE_INPUT_SWITCH_CHANNEL",
                    "groupIndex": 1,
                    "groups": [
                        "00000000-0000-0000-0000-000000000025",
                        "00000000-0000-0000-0000-000000000021"
                    ],
                    "index": 1,
                    "label": "",
                    "multiModeInputMode": "KEY_BEHAVIOR",
                    "on": true,
                    "profileMode": "AUTOMATIC",
                    "userDesiredProfileMode": "AUTOMATIC"
                }
            },
            "homeId": "00000000-0000-0000-0000-000000000001",
            "id": "xxxx",
            "label": "Wohnzimmer Beleuchtung",
            "lastStatusUpdate": 1587233145096,
            "liveUpdateState": "LIVE_UPDATE_NOT_SUPPORTED",
            "manufacturerCode": 1,
            "modelId": 404,
            "modelType": "HmIP-FSI16",
            "oem": "eQ-3",
            "permanentlyReachable": true,
            "serializedGlobalTradeItemNumber": "xxxx",
            "type": "FULL_FLUSH_INPUT_SWITCH",
            "updateState": "UP_TO_DATE"
        }`

**Comment by SukramJ** [comment]
Please use the output of the dump. This dump is already anonymized, so no further replacement with xxx is needed. It is enough to send the device section of the fsi, but leave it in a file (formatted). Then upload it to https://gist.github.com/ and add a link here.

**Comment by Neisi** [comment]
https://gist.github.com/Neisi/213c24fb38f816e9a5cd5e5d36c089d5

**Comment by helfm** [comment]
Thank you for your support Neisi, SukramJ and CoreGreenberet.

You're all doing a great job -  many thx.

regards Markus

**Comment by helfm** [comment]
Hi colleagues,

I do not want to stress the topic, just ask if there are already news on this topic?
Sorry about the inquiry, I know I'm impatient.

Best regards Markus

**Comment by coreGreenberet** [comment]
Sorry I haven't had time for this yet. I think I can implement this on the weekend in the library. After that @SukramJ can put it into home assistant

**Comment by helfm** [comment]
Thx for your response coreGreenberet.

regards Markus

**Comment by Neisi** [comment]
@SukramJ , has the FSI16 been integrated in the HA commit #36595 ? unfortunately I miss this one there, could it be? Thanx

**Comment by SukramJ** [comment]
@Neisi that's correct. #320 must be releases before integration of FSI16 in HA can happen.

**Comment by coreGreenberet** [comment]
ah sorry i thought i'Ve packed that already in a new release.
i think I have time for that on thurstday

**Comment by helfm** [comment]
Hi @Neisi,

I'm not sure I'm getting this right. Will this expansion be part of an upcoming Hassio version? Can you say which version that will be?

Regards Markus

**Comment by Neisi** [comment]
Works fine from 0.113.0

**Comment by h3ad912** [comment]
Workshop fine by ne, too.

Thank you 👍🏼

**Comment by helfm** [comment]
@Neisi, thx.

Hmmm, Gotta look again. Can't find it.

Regards Markus

**Comment by helfm** [comment]
Maybe someone can give me a tip.

I use a Raspberry with the RaspberryMatic version: 3.51.6.20200621

The HomeAssistant software runs on another Raspberry with version: 0.113.1

When I integrate the HmIP-FSI16 into the RaspberryMatic, it still does not appear in HomeAssistant. This should work now on the hassio version: 0.113.1.
What am I doing wrong?

thx in advance Markus

**Comment by coreGreenberet** [comment]
raspberrymatic is the issue here. this library is for using homematicip with the access point and not with the (O)CCU

**Comment by helfm** [comment]
Thanks coreGreenberet,

That means I need an extension in the RaspberryMatic version?

All previous components are recognized and work without problems.

Regards Markus

**Comment by Neisi** [comment]
Home assistant has two homematic integrations.
"Homematic" (   https://www.home-assistant.io/integrations/homematic/  ) and "homematic IP cloud" (https://www.home-assistant.io/integrations/homematicip_cloud/).
You use the first one? This uses pyhomematic -> https://github.com/danielperna84/pyhomematic
There is also an open issue with the FSI16 (https://github.com/danielperna84/pyhomematic/issues/28)
But it looks like the owner doesn't have time to work on the project :-( But take a look at the wiki page.
But this is all offtopic here :-) *sry*

**Comment by helfm** [comment]
Thx Neisi
