### ISSUE TITLE
HomeMatic IP Cloud-Zugriffspunkt no green

### ISSUE THREAD

**Issue by JogiBarbarski** [coreGreenberet/homematicip-rest-api#313]
Hello, first of all many thanks for the great job you did there. I can't get the HMIP adapter to work. It is not possible to save the settings after entering the adapter data. And the errors from the log of the Raspberry Pi 4 look like this. Software and Raspberry Pi 4 are up to date. Best regards and thanks for everything.
hmip.0	2020-04-24 11:06:11.067	error	(8452) error starting homematic: Error: undefined is not a valid state value
hmip.0	2020-04-24 11:05:31.450	error	at WebSocket.emit (events.js:198:13)
hmip.0	2020-04-24 11:05:31.450	error	at WebSocket._ws.on (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
hmip.0	2020-04-24 11:05:31.450	error	at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
hmip.0	2020-04-24 11:05:31.450	error	at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:285:28)
hmip.0	2020-04-24 11:05:31.450	error	at HmIpCloudAccesspointAdapter._updateHomeStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:738:28)
hmip.0	2020-04-24 11:05:31.450	error	at HmIpCloudAccesspointAdapter.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1577:16)
hmip.0	2020-04-24 11:05:31.450	error	at new Promise (<anonymous>)
hmip.0	2020-04-24 11:05:31.450	error	at Promise (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1578:16)
hmip.0	2020-04-24 11:05:31.450	error	at HmIpCloudAccesspointAdapter.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5744:21)
hmip.0	2020-04-24 11:05:31.450	error	at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39
hmip.0	2020-04-24 11:05:31.450	error	(7357) Error: undefined is not a valid state value
hmip.0	2020-04-24 11:05:31.449	error	(7357) uncaught exception: undefined is not a valid state value
hmip.0	2020-04-24 11:05:31.105	error	at WebSocket.emit (events.js:198:13)
hmip.0	2020-04-24 11:05:31.105	error	at WebSocket._ws.on (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
hmip.0	2020-04-24 11:05:31.105	error	at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
hmip.0	2020-04-24 11:05:31.105	error	at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:285:28)
hmip.0	2020-04-24 11:05:31.105	error	at HmIpCloudAccesspointAdapter._updateHomeStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:738:28)
hmip.0	2020-04-24 11:05:31.105	error	at HmIpCloudAccesspointAdapter.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1577:16)
hmip.0	2020-04-24 11:05:31.105	error	at new Promise (<anonymous>)
hmip.0	2020-04-24 11:05:31.105	error	at Promise (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1578:16)
hmip.0	2020-04-24 11:05:31.105	error	at HmIpCloudAccesspointAdapter.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5744:21)
hmip.0	2020-04-24 11:05:31.105	error	at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39
hmip.0	2020-04-24 11:05:31.105	error	(7357) Error: undefined is not a valid state value
hmip.0	2020-04-24 11:05:31.076	error	(7357) uncaught exception: undefined is not a valid state value
hmip.0	2020-04-24 11:04:29.185	error	(7357) error starting homematic: Error: undefined is not a valid state value

**Comment by steckenpferd** [comment]
Hi - here is not the ioBroker support- please ask your questions here: https://github.com/iobroker-community-adapters/ioBroker.hmip

Thank you

**Comment by JogiBarbarski** [comment]
OK sorry. Have a good time
