### ISSUE TITLE
Home Assistant does not support "Homematic IP Window  / Door Contact - optical, plus"

### ISSUE THREAD

**Issue by tose60** [coreGreenberet/homematicip-rest-api#315]
Tried to integrate a "Homematic IP Window  / Door Contact - optical, plus" into my setup. 
(door contact with two batteries). This device seems not to be supported yet. I get the following error message in "Home Assistant".

'SHUTTER_CONTACT_OPTICAL_PLUS' isn't a valid option for class 'DeviceType'
16:28:03 – components/homematicip_cloud/hap.py (WARNING)

'SHUTTER_CONTACT_OPTICAL_PLUS' isn't a valid option for class 'DeviceType'
16:28:03 – components/homematicip_cloud/hap.py (WARNING)

Can anybody help to get this devices added to "Home Assistant"? #311

**Comment by coreGreenberet** [comment]
I don't have the device. Could you please post your (anonymized) ap configuration?

**Comment by tose60** [comment]
Attached the requested (anonymized) HomeMatic AP configuration file. 

[hmip-config_477F.json.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/4624717/hmip-config_477F.json.txt)
