### ISSUE TITLE
Can not integrate HmIP-FROLL

### ISSUE THREAD

**Issue by helfm** [coreGreenberet/homematicip-rest-api#316]
Dear members,

I have problems integrating a HomeMatic-IP device: Shutter actuator for flush-mount (HmIP-FROLL)

According to the page: https://www.home-assistant.io/integrations/homematicip_cloud/, the integration should be possible.
Unfortunately the device is not shown in the entity list.

Does anyone know the solution?

My Configuration:
RaspberryMatic 3.51.6.20200420
HassOS 3.13
Home Assistant 0.109.6

Many thanks Markus

**Comment by coreGreenberet** [comment]
The given module is for homematicip with an access point. Not with (O)CCU!

**Comment by helfm** [comment]
I dont know why, after 2 hours it is in hassio. No action needed.

thx
