### ISSUE TITLE
HmIPW - config

### ISSUE THREAD

**Issue by steckenpferd** [coreGreenberet/homematicip-rest-api#322]
Hi,

Can anybody share his HmIPW config?

https://technikkram.net/blog/2020/06/10/homematic-ip-wired-neues-zur-einrichtung-mit-der-homematic-ip-app/

**Comment by mengelh** [comment]
Hello,

the integration of the HmIPW-DRAP into the Homematic IP App described in the linked article works for me without problems, exactly as described in the article.

Greetings

**Comment by steckenpferd** [comment]
@mengelh perfect - can you than share your anonymous config?

See here how to:
https://github.com/coreGreenberet/homematicip-rest-api/issues/150

**Comment by coreGreenberet** [comment]
@mengelh thanks. Will be implemented in PR #327

**Comment by steckenpferd** [comment]
@SukramJ can you add now HmIPW-DRAP and the HMIPW devices to Home Assistant?

**Comment by coreGreenberet** [comment]
sadly not yet. there is something wrong with running the test suite :/
it works fine running them at home or single tests on linux, but running the whole suite generates errors :/

**Comment by SukramJ** [comment]
Hi @steckenpferd ,
i think it requires some PR to add the functionality to HA, after this lib has been **released**.

1. update dependency for this lib (get rid off lots of warnings in the HA log)
2. Add HmIP-STV
3. add options to HA config_flow to allow HmIP-devices with multiple channels like (HMIP-MOD-OC8 an especially the HMIPWxxx) to be split to multiple HA-devices. This allows individual area assignment on a channel base.
4. Add HMIPW-DRD3, HMIPW-DRS8, HMIPW-DRI32

Smaller pull requests a faster in HA.
I hope 1 and 2 can be part of 0.115.

BR

**Comment by coreGreenberet** [comment]
yay I finally got it to work, so this can now be implemented in ha =)
