### ISSUE TITLE
enable angle sensor HMIP-STV

### ISSUE THREAD

**Issue by rschoell** [coreGreenberet/homematicip-rest-api#328]
Dear developer's, 
thanks for delivering such a great addon. I've recently purchased an acceleration and angle sensor HMIP-STV. 
if you could please add this to the devices. I'm using the angle mode. 
you'll need to evaluate, if "accelerationSensorTriggered" is true or false.

Please find attached the dumps from HMIP
[hmip-config_586C_angle_detected.json.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5141580/hmip-config_586C_angle_detected.json.txt)
[hmip-config_586C_angle_not detected.json.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5141581/hmip-config_586C_angle_not.detected.json.txt)

Appreciate you working on implementing this sensor. 
Please let me know, in which release it'll be usable.

thanks
Ralph

**Comment by rschoell** [comment]
Thank you very much for the quick implementation. I much appreciate your hard work on this!
Will this be live in the next release then?

**Comment by coreGreenberet** [comment]
well there is currently an issue with the test suite. It's failing on circleci, but running fine on my machines. As soon as this is working fine I will publish a new release

**Comment by rschoell** [comment]
Great work! I installed the prerelease of HomeAssistant and the hmip-stv works as expected!!!
