### ISSUE TITLE
Blinds Module HmIP-HDM1

### ISSUE THREAD

**Issue by bonsaijogi** [coreGreenberet/homematicip-rest-api#332]
Please integrate the new Blinds Module HmIP-HDM1 from Hunter Douglas powered by Homematic IP.
Until now only the battery charge is displayed.

Thanks

[hmip-hdm1.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5214163/hmip-hdm1.txt)

**Comment by coreGreenberet** [comment]
It's complicated to get all "set" methods.
Do you need to modify (via api/homeassistant/..) anything else than primary & secondary shading level?
