### ISSUE TITLE
Home Assistant installed on Synology DS918+ not polling Homematic-IP

### ISSUE THREAD

**Issue by eL-Zotto** [coreGreenberet/homematicip-rest-api#333]
Hello

I installed and configured Home Assistant on my Synology DS918+ yesterday. I used the homeassistant package and NOT hassio!
I can open the page on port 8123 and went through the first steps, where I integrated my Homematic-IP AccessPoint.
I see all my Homematic devices and grouped them according the rooms they are located in.
When I chack a temperature senor, I only see 1 tick (measured value), taken at the time I configured my AccessPoint (24 hours ago).
No new ticks seem to be collected. When I restart the homeassistant service on my DS, a new tick will be taken.
What went wrong?
Thank you for your support

Regards
Laurent

**Comment by coreGreenberet** [comment]
Hello,

Pleaso open the issue in https://github.com/home-assistant/core

This is just the backend library which gets used by home assistant. 
My guess is that HA cant do the connection to the websocket.
