### ISSUE TITLE
Config dump with newer AP FW

### ISSUE THREAD

**Issue by SukramJ** [coreGreenberet/homematicip-rest-api#335]
Hi,

i updated an AP with the latest FW (over CCU)
[Here](https://gist.github.com/SukramJ/e08c3b52014bbd7268d4b5643204987d) is a new dump.

Noteworthy is a dedicated device for the AP

BR

**Comment by coreGreenberet** [comment]
The cloud firmware/settings are having this too already.
Its also in the current head =)
```python
self.accessPointUpdateStates
```

**Comment by SukramJ** [comment]
Hi,

there is no HOME_CONTROL_ACCESS_POINT and no ACCESS_CONTROLLER_CHANNEL in current head!

BR

**Comment by coreGreenberet** [comment]
Oh I've overseen that
