### ISSUE TITLE
'HOME_CONTROL_ACCESS_POINT' isn't a valid option for class 'DeviceType'

### ISSUE THREAD

**Issue by HansDampfwurst** [coreGreenberet/homematicip-rest-api#340]
## The problem

Logger: homematicip.base.enums
Source: /usr/local/lib/python3.8/site-packages/homematicip/base/enums.py:33
First occurred: 20. Oktober 2020, 13:57:26 (1754 occurrences)
Last logged: 10:14:48

    'HOME_CONTROL_ACCESS_POINT' isn't a valid option for class 'DeviceType'
    'ACCESS_CONTROLLER_CHANNEL' isn't a valid option for class 'FunctionalChannelType'

## Environment

- Home Assistant Core release with the issue: Home Assistant 0.116.4
- Last working Home Assistant Core release (if known): Home Assistant 0.116.4
- Operating environment (OS/Container/Supervised/Core): HassOS 4.14
- Integration causing this issue: homematicip_cloud
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/homematicip_cloud/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```Logger: homematicip.home
Source: /usr/local/lib/python3.8/site-packages/homematicip/home.py:365
First occurred: 20. Oktober 2020, 13:57:26 (2 occurrences)
Last logged: 20. Oktober 2020, 13:57:57
There is no class for device 'HOME_CONTROL_ACCESS_POINT' yet 



Logger: homematicip.device
Source: /usr/local/lib/python3.8/site-packages/homematicip/device.py:194
First occurred: 20. Oktober 2020, 13:57:26 (882 occurrences)
Last logged: 10:24:34
There is no class for functionalChannel 'ACCESS_CONTROLLER_CHANNEL' yet 



Logger: homematicip.base.enums
Source: /usr/local/lib/python3.8/site-packages/homematicip/base/enums.py:33
First occurred: 20. Oktober 2020, 13:57:26 (1766 occurrences)
Last logged: 10:24:34

    'HOME_CONTROL_ACCESS_POINT' isn't a valid option for class 'DeviceType'
    'ACCESS_CONTROLLER_CHANNEL' isn't a valid option for class 'FunctionalChannelType'

```

## Additional information

Der Fehler scheint erst seit dem 20.10.2020 aufzutreten. Vielleicht gab es wieder Anpassungen durch durch den Hersteller an der Cloud. Auf der anderen Seite sieht es fasst wie hier https://github.com/home-assistant/core/issues/40402 aus, aber das ist ja mit einer CCU.

In der Homematic IP App wird auch bei allen 3 HmIP-Broll das Zeichen für Funkstörung angezeigt. Eine Bedienung über die App ist dennoch möglich. Auch Automatisierungen und Steuerung über Google Home funktionieren.

HmIP-HAP v 2.2.18 (wobei ich noch Anfang dieser Woche auf 2.0.36 war)

**Comment by HansDampfwurst** [comment]
[hmip-config_4668.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/5414542/hmip-config_4668.zip)

**Comment by coreGreenberet** [comment]
Danke, das wurde bereits eingemeldet. Ich bin nur leider noch nicht dazu gekommen es einzubauen.

Duplicate of #335

**Comment by SpongeSeb** [comment]
Hi, Sorry ich bin neu hier und muss direkt mal fragen. Gibt es nun ein Lösung zu dem Thema?
Ich habe genau das selbe Problem das mir der Log mit dieser Meldung vollgehauen wird.

Gruss Danke

**Comment by coreGreenberet** [comment]
ist in der library bereits erledigt. Im Homeassistant wird es vermutlich in der nächsten oder übernächsten version gefixt sein
