### ISSUE TITLE
How to get the valve signal of HMIP-BWTH via API?

### ISSUE THREAD

**Issue by chgoeldi** [coreGreenberet/homematicip-rest-api#341]
Does the API reveal the valve signal of the Wall Thermostat HMIP-BWTH? Or how can one read from the API whether the valve is currently open or not?

**Comment by coreGreenberet** [comment]
Well the BWTH doesn't have a valve. You would need to reed the attributes of the e.g. HMIP-eTRV.

The [valvePosition](https://homematicip-rest-api.readthedocs.io/en/latest/homematicip.html#homematicip.device.HeatingThermostat.valvePosition) attribute contains that information.

**Comment by chgoeldi** [comment]
Wow, thanks for the quick reply!
Yes, I know that the Thermostat doesn't have a valve itself. But it gives the valve a signal via wire. Question is whether that signal can be read from the BWTH somehow (it also doesn't shop up in the App).

**Comment by coreGreenberet** [comment]
The BWTH has a "INTERNAL_SWITCH_CHANNEL" functional Channel. Which has an "internalSwitchOutputEnabled" attribute. I don't have one, so I can't test it, but maybe you can get the desired value from there

**Comment by chgoeldi** [comment]
Thanks a lot for the hint. Unfortunately, the attributes in the "INTERNAL_SWITCH_CHANNEL" all only refer to settings and not to the values calculated within the BWTH or the signal it then derives to steer the valve. As far as I understand the "internalSwitchOutputEnabled" setting turns the valve signal on or off (it also can be set via App).
Any other ideas whether and how it can be read from the BWTH if it currently sends an "open" or "close" valve signal?

**Comment by coreGreenberet** [comment]
then I dont think, that this state is avaialable in the api :/
you can try to dump the configuration during heating and during "non" heating and check if there is any difference

**Comment by mayrd** [comment]
Also was looking for this as it is also not in the app. I wrote to the eq-3 support and would let you know if there is an option.

**Comment by coreGreenberet** [comment]
@mayrd don't get too much hope. Eq3 isn't really interested in helping 3th party apps :(
