### ISSUE TITLE
Access Point is not a valid Device

### ISSUE THREAD

**Issue by flammermann** [coreGreenberet/homematicip-rest-api#345]
I receive the following warnings since this noon, it could be related to an Homematic IP app update (version 2.4.3) that came in today for me.

```
'HOME_CONTROL_ACCESS_POINT' isn't a valid option for class 'DeviceType'
There is no class for device 'HOME_CONTROL_ACCESS_POINT' yet
```

```
'ACCESS_CONTROLLER_CHANNEL' isn't a valid option for class 'FunctionalChannelType'
There is no class for functionalChannel 'ACCESS_CONTROLLER_CHANNEL' yet
```

Could you help me understand where there warnings are coming from and how to resolve the underlying problem(s)?

**Comment by coreGreenberet** [comment]
There was an update of the cloud and I haven't had time to catch it up yet.
At the moment you can just be patient until I've updated the library. I try to get it done on the weekend.

This got already reported it #335

**Comment by flammermann** [comment]
Sorry I didn't see the issue 335 before, thanks for the hint.
Also thanks for all the great work you have done so far!
