### ISSUE TITLE
Adding support for HmIP-WGC (Garatentortaster)?

### ISSUE THREAD

**Issue by shakerCH** [coreGreenberet/homematicip-rest-api#346]
Hi. I have a Garagentortaster (garage door button) HmIP-WGC. As it's currently not supported by the HomematicIP REST API - is there anything I can do to help getting it integrated?

**Comment by coreGreenberet** [comment]
hi,
please create a config dump. See #114 for a howto.
But I doubt, that there is much that I can implement here as the api isn't providing any button events. :/

**Comment by coreGreenberet** [comment]
I'm closing this now as I didn't received  a response for almost 4 months
