### ISSUE TITLE
High Duty Cycle afte Update to HA 0.117.2

### ISSUE THREAD

**Issue by HansDampfwurst** [coreGreenberet/homematicip-rest-api#347]
## The problem

  After update Home Assistant from 0.116.4 to 0.117.2 Homematic IP Duty Cycle increase from under 20% to between 30 and 60%

## Environment

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.6
supervisor | 2020.10.1
timezone | Europe/Berlin
version | 0.117.2
virtualenv | false

- Home Assistant Core release with the issue: 0.117.2
- Last working Home Assistant Core release (if known): 0.116.4
- Operating environment (OS/Container/Supervised/Core): HassOS 4.15
- Integration causing this issue: HomematicIP Cloud
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/homematicip_cloud/

## Traceback/Error logs
no Error Logs 

## Additional information
reboot does not solve the problem
HmIP-STH bringt seit dem Update gestern kurz vor 19:00 Uhr auch viel mehr Messwerte als vor dem Update

Duty Cylce - 5 days
![Home Assistant](https://user-images.githubusercontent.com/66558871/97972521-ef44ef80-1dc4-11eb-8c56-8d42107a4a46.png)
HmIP-STH - 24h
![HmIP-STH-5days](https://user-images.githubusercontent.com/66558871/97972824-67131a00-1dc5-11eb-8367-24b2ed883b85.png)
HmIP-STH - 5 days
![HmIP-STH-24h](https://user-images.githubusercontent.com/66558871/97972825-67abb080-1dc5-11eb-90c3-6cabdfb48282.png)

**Comment by coreGreenberet** [comment]
Please open an issue on https://github.com/home-assistant/core. This library just gets used by HA, but I'm not maintaining the HA compontents.

**Comment by HansDampfwurst** [comment]
Sorry, my fault. 
After power off on again HmIP-STH it seems to be fine now.
![DC-5days-12h](https://user-images.githubusercontent.com/66558871/97991778-283f8d00-1de2-11eb-9ca3-9dd630cfe85c.png)
