### ISSUE TITLE
Device HmIP-DRBLI4 (Jalousieaktor/Blinds Actuator) missing?

### ISSUE THREAD

**Issue by kochmilch** [coreGreenberet/homematicip-rest-api#348]
Hello everyone
I just had new devices installed and I was hoping that they could be easily integrated. Unfortunately they do not seem to be supported. Am I wrong? Unfortunately I'm not sure if I'm posting this one correctly either.

Is there a way to get them running?
Thanks for the support and best regards. 

**HmIP-DRBLI4**, (Funk-Jalousieaktor für Hutschienenmontage, 4-fach)
HMIP-DRBLI4 (Blinds Actuator – 4x channels, 230V, 2,2A / 500W per channel) electrical DIN rail

appendix: dump file from homematicip_cloud.dump_hap_config
[hmip_config_XXXX.json.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5482190/hmip_config_XXXX.json.txt)

**Comment by coreGreenberet** [comment]
the attached configuration looks fine for integrating it.

**Comment by kochmilch** [comment]
Oh wow. That fast? Just like that? That's amazing, coreGreenberet. Thank you so much. It will make sure that the Homematic-System is accepted by the ladies of the family. Which is not so easy :D Thank you so much.

**Comment by coreGreenberet** [comment]
Well i didnt integrate it yet, I've just checked the configuration:D

**Comment by kochmilch** [comment]
...which I consider already to be great and amiable :) Thank you.

**Comment by coreGreenberet** [comment]
Thanks to @SukramJ he implemented it in #361

**Comment by kochmilch** [comment]
You guys are awesome!!! Thank you so much. Flawlessly working :D
