### ISSUE TITLE
asyncio implementation..

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#35]
I am wondering whether you have considered implementing an asyncio version, especially implementing the aiohttp request and websocket component ?

I did a fork and started doing it myself, just to realise this means practically rewriting the whole package.
But I'd still like to put effort in achieving this. Do you have any ideas or plans for a more integrated approach? 
Again, I'd love to help.

Sander.

**Comment by coreGreenberet** [comment]
Actually not at the moment. 
I've implemented the api mostly in python 2.7 (and started support for 3 a while later), because on many surveys you can see that the majority of python users are still using 2.7.
asyncio isn't working on 2.7 =(

**Comment by sander76** [comment]
I see.
I want to use your library for writing a plug-in for home assistant.
https://home-assistant.io

Can be threaded but prefers asyncio. It is python3 only though..

**Comment by mxworm** [comment]
Hi sander76,

I already started to implement a home assistant component.  
-> https://github.com/mxworm/home-assistant-custom

**Comment by sander76** [comment]
@coreGreenberet 
I played around with an async implementation of your library.
For a rough version look here:

https://github.com/sander76/homematicip-rest-api/tree/async

But the implementation is a lot of duplication of efforts as each method that does a restcall needs to be rewritten as an async one.
So the question now is how I should proceed and I'd like your opinion. There are basically two options:

1. I do a complete fork of your library and rewrite it for async functionality.
2. We implement an async option inside your library.

I prefer option2. As I think it is better maintainable but for a proper async implementation that requires some changes to your code as well. For example take the `Home` class and its method `set_security_zones_activation`.
There we need to separate the dict from the actual restcall. This would look like:

```Python
class HomeBase:
    def _set_security_zones_activation(self, internal=True, external=True)
        return {"zonesActivation": {"EXTERNAL": external, "INTERNAL": internal}}

class Home(HomeBase):
    def set_security_zones_activation(self, internal=True, external=True):
        data = self._set_security_zones_activation(internal,external)
        return self._restCall("home/security/setZonesActivation", json.dumps(data))

class AsyncHome(HomeBase):
    @asyncio.coroutine
    def set_security_zones_activation(self, internal=True, external=True):
        data = self._set_security_zones_activation(internal,external)
        return yield from self._restCall("home/security/setZonesActivation", json.dumps(data))
```

Obviously I need your ok and help with this... What do you think ?

**Comment by sander76** [comment]
@coreGreenberet  Sorry for pushing you, but can you let me know what you think of my proposal ? I'd really like to get started...

**Comment by sander76** [comment]
@coreGreenberet Can you let me know what you think ? I really think your project is interesting and I'd like to put effort in it, but if you don't feel like it (like accepting pull requests and such) please let me know and I'll try and find another solution.

**Comment by coreGreenberet** [comment]
@sander76 sorry I was really busy with my work, so I didn't check Github in the last month.
I like Option 2, but I'm also thinking about dropping support for python 2.7 and continue with 3.
Therefore we won't have to implement everything 2 times.

**Comment by sander76** [comment]
@coreGreenberet 👍 
Your current implementation would be a threaded one. I'd really like to do an async one too. So supporting both (which makes perfect sense to me) would require a slight architecture change so both can share as much code as possible.

My suggestion would be as described above where you create separate function calls to:

- the creation of body data which used to make the api call.
- `from_json` method for parsing of incoming data.

Another suggestion would be to move the connection data inside a class that will make it possible to have multiple hmip hubs running inside the same program. (thinking about homeassistant.io implementation)

I'll take some more time for a more detailed proposal.

**Comment by sander76** [comment]
@coreGreenberet In addition to my previous post:

```python
# **************************
# Current implementation 
# **************************

class HomeMaticIpObject():
    def _restCall(self, url, body=None):
        # contains the actual restcall.
        pass


class Home(HomeMaticIpObject):
    def from_json(self, js_data):
        pass


class Device(HomeMaticIpObject):
    def from_json(self, js_data):
        pass


class PlugableSwitch(Device):
    def from_json(self, js_data):
        super().from_json(js_data)
        # and do other stuff

    def set_switch_state(self, on=True):
        data = {"channelIndex": 1, "deviceId": self.id, "on": on}
        return self._restCall("device/control/setSwitchState",
                              body=json.dumps(data))

# **************************
# Suggested new implementation 
# **************************

class BaseConnection():
    """All connection specific data like tokens,ids, urls
    etc are stored here"""
    def __init__(auth_token, access_point_id):
        self._auth_token = auth_token
        self._access_point_id

    def init_connection(lookup=True):
        """Do the hmip url lookup init"""
        pass

    def _restCall(url, body):
        pass


class AsyncConnection(BaseConnection):
    def __init__(self, loop, auth_token, access_point_id):
        super().__init__(auth_token, access_point_id)
        self._websession = aiohttp.ClientSession(loop=loop)

    async def _restcall(self, url, body):
        """async api call"""
        _resp = await self._websession.get(url, body)
        # do other stuff...

    async def init_connection(self, lookup=True):
        """Do the async hmip url lookup init"""
        pass


class ThreadedConnection(BaseConnection):
    def __init__(self, auth_token, access_point_id):
        super().__init__(auth_token, access_point_id)

    def _restCall(self, url, body):
        """api call"""
        _resp = self._request.get(url, body)
        # do stuff.

    def init_connection(self, lookup=True):
        """Do hmip url lookup init"""
        pass


class BaseDevice():
    def __init__(self, connection):
        self._connection = connection

    def from_json(self, js_data):
        pass


class BasePlugableSwitch(BaseDevice):
    def from_json(self, js_data):
        super().from_json(js_data)
        # and do other stuff

    def _set_switch_state(self, on=True):
        """Returns the url and body of the call"""
        url = 'device/control/setSwitchState'
        data = {"channelIndex": 1, "deviceId": self.id, "on": on}
        return url, json.dumps(data)


class AsyncPlugableSwitch(BasePlugableSwitch):
    def __init__(self, connection):
        super().__init__(connection)

    async def set_switch_state(self, on=True):
        url, data = self._set_switch_state(on)
        await self.connection._restcall(url, data)


class ThreadedPlugableSwitch(BasePlugableSwitch):
    def __init__(self, connection):
        super().__init__(connection)

    def set_switch_state(self, on=True):
        url, data = self._set_switch_state(on)
        self.connection._restcall(url, data)

```

**Comment by sander76** [comment]
Are you still very busy the upcoming days/weeks? I'd like to spend time on this and do some pull requests, but then I like to know whether you are able to handle them...

**Comment by coreGreenberet** [comment]
just do them I will try to review them as quickly as possible.
and thanks for the help =)

**Comment by sander76** [comment]
@coreGreenberet Great! Thanks!

**Comment by sander76** [comment]
@coreGreenberet Can you create a branch where I can do pull requests ?

**Comment by coreGreenberet** [comment]
done
