### ISSUE TITLE
Warning FULL_FLUSH_CONTACT_INTERFACE_6

### ISSUE THREAD

**Issue by Manuel-1982** [coreGreenberet/homematicip-rest-api#352]
Hello everyone,
I put my issue on the wrong space [here](https://github.com/home-assistant/core/issues/42766) 
Thx to SukramJ for telling me I have to put it in here.

I'm not sure, but i think the Warning FULL_FLUSH_CONTACT_INTERFACE_6 is realted to the HMIP-FCI6.
It would be great if it will be included in the future.

In the appendix you find the dump file from homematicip_cloud.dump_hap_config
[hmip-config_C88A.json.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5496529/hmip-config_C88A.json.txt)

**Comment by coreGreenberet** [comment]
Thanks to @SukramJ he implemented it in #361
