### ISSUE TITLE
HomematicIP HmIP-DRSI4

### ISSUE THREAD

**Issue by gewonet** [coreGreenberet/homematicip-rest-api#355]
Dear all,

is it  possible to use hmip-drsi4 with 
[hmip-config_8DDF.json.log](https://github.com/coreGreenberet/homematicip-rest-api/files/5536875/hmip-config_8DDF.json.log)
homeassitant?

**Comment by coreGreenberet** [comment]
Thanks to @SukramJ he implemented it in #360
