### ISSUE TITLE
getting fiddler to work

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#36]
Trying to get fiddler to work, so I can help with this repo, but can't get fiddler to work. It gets stuck at trying to "login"... Any idea how to solve this ?

![image](https://user-images.githubusercontent.com/1688712/30119622-9e7f4cfc-9326-11e7-8aae-d5f66cf86c35.png)

**Comment by sander76** [comment]
@coreGreenberet Do you need to keep this your secret or is this something you can share? ;-)
More in general: Is it possible to share how you got any sniffing tool to work ?
(I tried fiddler and pcap)

**Comment by coreGreenberet** [comment]
You have to make a so called "Men in the middle Attack".

1. Run fiddler/charles/....
1. export the root ca of the applicaiton and install it on your mobile phone. ( each application will generate it's own CA)
1.  Press the "Decode" button in fiddler
1. configure your computer as a proxy in the network settings from your mobile device
1. as soon as the traffic goes in you should see the decrypted messages. If it isn't working try to select the stream and do a right click -> decode this stream
