### ISSUE TITLE
Homematic IP Cloud  HMIP-DRSI4

### ISSUE THREAD

**Issue by gewonet** [coreGreenberet/homematicip-rest-api#368]
I have an HMIP-DRSI4 with Homematic IP Cloud and would like to use it in Home Assistant.
Is it possible to integrate this din rail switch?

thx Gerhard
[hmip-config_8DDF.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/5695104/hmip-config_8DDF.zip)

**Comment by SukramJ** [comment]
Hi,
as you can see from the readme it is already integrated in this repo.
You need to wait until version 2021.1.0 until release in HA.

BR

**Comment by gewonet** [comment]
Thank you!

**Comment by SukramJ** [comment]
Please close this issue.
