### ISSUE TITLE
Add dimmer support

### ISSUE THREAD

**Issue by chbndrhnns** [coreGreenberet/homematicip-rest-api#37]
When I list my devices, I get the message:

```
homematicip.home - WARNING - There is no class for PLUGGABLE_DIMMER yet
```

Could you add support for a dimmer so that the lights can be dimmed?

**Comment by coreGreenberet** [comment]
I don't have a dimmer myself, so I cant look at it myself.
could you please use the latest commit and give me the output from "python3 homematic_cli.py --dump-configuration"?
With that Information I would be able to implement it.

**Comment by chbndrhnns** [comment]
[config.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/1479732/config.txt)

👍

**Comment by coreGreenberet** [comment]
thanks
I've removed the file so you don't expose all the data to the public

**Comment by coreGreenberet** [comment]
@chbndrhnns it is added. also set_dim_level() should theoretically work. I couldn't test it.
