### ISSUE TITLE
Fenstererkennung deaktivieren?

### ISSUE THREAD

**Issue by florian84z** [coreGreenberet/homematicip-rest-api#372]
Ein großes "DANKE" für diesen tollen Adapter. 

Ist es möglich, die Fenster-offen-Erkennung mittels des Adapters zu deaktivieren? Ich habe über ioBroker und den Aqara Fenstersensoren dies realisiert, leider funkt mir dann aber -ab und zu- die interne Erkennung dazwischen.

**Comment by coreGreenberet** [comment]
Nicht direkt, man könnte nur den Aktor aus der Heizungsgruppe vom Raum entfernen, aber das kann man auch über die APP einfach machen
