### ISSUE TITLE
Is the integration of the HMIP-DRSI1 planned?

### ISSUE THREAD

**Issue by oneteam2win** [coreGreenberet/homematicip-rest-api#373]
Is the integration of the HMIP-DRSI1 planned?
I have seen that the HMIP-DRSI4 has already been implemented.
Thanks for a feedback and great integration.

**Comment by coreGreenberet** [comment]
planned is the wrong word. We can only implement devices which we have / from which we are getting a configuration.
If you have one, you could post your configuration as described in #114

**Comment by oneteam2win** [comment]
Thank you very much for the quick feedback.
Hopefully you will find the information you need in the attachment.
In it you should find the information about the HmIP-DRSI1 as well as the wall switch HmIP-WRCC2.
[hmip-config_640F.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5798663/hmip-config_640F.txt)

**Comment by oneteam2win** [comment]
I've seen that I need to create a GIST File. Hope this is okay now.

for the HmIP-DRSI1
https://gist.github.com/oneteam2win/4bc61dfeda9d6686d90e6fee9a9ed101

for the HmIP-WRCC2
https://gist.github.com/oneteam2win/6ddf0541ef1f4ca863b6049663dabb7c

**Comment by coreGreenberet** [comment]
The gist wasn't really necessary. Many people have just posted the whole config as a comment which made the comment just too big =)

**Comment by coreGreenberet** [comment]
I've just checked the files. The devices are not covered completely.

**Comment by oneteam2win** [comment]
Sorry, my mistake.
I thought I only copying the part that concerns the two devices.
In the attachment now the complete excerpt.
[hmip-config_640F.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5814715/hmip-config_640F.txt)

**Comment by coreGreenberet** [comment]
> 
> 
> Sorry, my mistake.
> I thought I only copying the part that concerns the two devices.
> In the attachment now the complete excerpt.
> [hmip-config_640F.txt](https://github.com/coreGreenberet/homematicip-rest-api/files/5814715/hmip-config_640F.txt)

thanks that file is perfect
well you didn't copy all the required parts. You've cutted out half of the settings.
