### ISSUE TITLE
How to get device ID

### ISSUE THREAD

**Issue by MoonTM-GIT** [coreGreenberet/homematicip-rest-api#374]
How do you get the device ID?

I just cant figure it out, I thought it was the SGTIN but that is apparently not the case.

**Comment by danross** [comment]
If "device" is your device object you should call "device.id"

**Comment by MoonTM-GIT** [comment]
Alright, I will try that later. Maybe I just missed this one but im so certain, that I tried so many combinations of something similar to this.

**Comment by MoonTM-GIT** [comment]
Wow, that actually worked. I was so sure I tried this

Thank you very much!
