### ISSUE TITLE
Vote: Drop Python 2.7 support?

### ISSUE THREAD

**Issue by coreGreenberet** [coreGreenberet/homematicip-rest-api#38]
Hello,

I'm thinking of dropping the support for python 2.7 and just use 3.X in the future. I've started the project with 2.7, because of some online surveys most people are still using 2.7. 3.X on the other hand has some nice features on which the project could really benefit from and implementing everything twice (e.g. for asyncio in 3.X) or check the compatibility on both python versions is really frustrating.

What do you guys think?

**Comment by sander76** [comment]
Django is now python3 only. So for me there is no question:
Python3 == Python
Python2 == Legacy Python and will be less supported as time passes.

So perfectly fine only supporting Python3

**Comment by marcsowen** [comment]
From the official Ubuntu 17.10 release notes:

"Python 2 is no longer installed by default. Python 3 has been updated to 3.6."

Source: https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes

I think this is another reason to switch to python 3.x.

**Comment by coreGreenberet** [comment]
okay than i Think it is settled...drop 2.7 and let us go back to the future!
