### ISSUE TITLE
How to upgrade to version 0.13.1?

### ISSUE THREAD

**Issue by oneteam2win** [coreGreenberet/homematicip-rest-api#384]
Unfortunately, I am not very familiar with the details of HA.
I have HA installed on a Synology in Docker.
I am currently using version 2021.1.5.

@Greenberet has provided a great integration for Homematic IP and thankfully keeps adding new devices.
The latest update seems to be tag 0.13.1.
Unfortunately I have no idea how I can check which SW status of the integration I currently have nor how I get to the latest SW status.
It would be nice if someone could help me here on a beginner level.
Thanks a lot!

**Comment by coreGreenberet** [comment]
I don't know if it is already in the current release of home-assistant, but 0.13.1 is already in the dev branch of HA, so it should be there with the next release.
