### ISSUE TITLE
HmIP-STE2-PCB

### ISSUE THREAD

**Issue by skornehl** [coreGreenberet/homematicip-rest-api#386]
Hi,

i just received my new HmIP-STE2-PCB and hope you have time to add it to your list of supported devices :)

https://gist.github.com/skornehl/a72c2dfdf7ce374e9336c3571cc8c454

Thank you! :)

**Comment by Sthreejay** [comment]
Did you manage to integrate the Device? I got mine today and in Home Assistant there is only the battery value presented.
