### ISSUE TITLE
Unable to getAuthToken

### ISSUE THREAD

**Issue by jmara** [coreGreenberet/homematicip-rest-api#39]
Hi,

I've tried to get a AuthToken for my homematicip but it keeps looping the https://lookup.homematic.com:48335/getHost call. 

Using the `clientCharacteristics` json and doing a curl post on the terminal results in Response code 400 INVALID_REQUEST:
`curl -X POST -d "json={'clientCharacteristics': {'applicationVersion': '1.0', 'language': 'de_DE', 'osType': 'Darwin', 'deviceType': 'Computer', 'applicationIdentifier': 'homematicip-python', 'osVersion': '15.6.0', 'apiVersion': '10', 'deviceManufacturer': 'none'}, 'id': '<my-id>'}" https://lookup.homematic.com:48335/getHost`

Do you have any idea how I can debug this?

Cheers,
Jan

**Comment by sander76** [comment]
Possibly ?

https://github.com/coreGreenberet/homematicip-rest-api/issues/26

**Comment by coreGreenberet** [comment]
I'm not so familiar with curl, but the post data doesn't need to include "json=" maybe thats the error?

**Comment by jmara** [comment]
I thought "json=" was the post-datafield but as I read the changelogs of the `requests` python module this option was introduced in 2.4.0 to post json data. 

Unfortunatly my local requests library was older (2.3.0). I've removed the `pass` from the __init__.py code and printed the raised error (I first thought it was an INVALID_REQUEST response, due to my curl checks) which is raised if `requests < 2.4.0`:
```
Traceback (most recent call last):
  File "generate_auth_token.py", line 16, in <module>
    homematicip.init(access_point)
  File "/Users/jm/homematicip/homematicip-rest-api/homematicip/__init__.py", line 66, in init
    result = requests.post("https://lookup.homematic.com:48335/getHost", json=clientCharacteristics,timeout=3)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

After upgrading to the latest version of `requests` its all working now :)
