### ISSUE TITLE
There is no class for device 'PUSH_BUTTON_FLAT' yet

### ISSUE THREAD

**Issue by oneteam2win** [coreGreenberet/homematicip-rest-api#391]
@coreGreenberet, 
Thank you again for the integration of the HMIP-DRSI1.
In my related thread #373 there was a second device,
the WRCC2 (Wall-mount Remote Control - flat), which is discussed in #380.
This should also already be recognised by the current HA.
However, I still get the following message every time I restart.
That's why I'm asking if you could check this again.
Thank you very much.

Logger: homematicip.home
Source: /usr/local/lib/python3.8/site-packages/homematicip/home.py:365
First occurred: 10:33:14 (1 occurrences)
Last logged: 10:33:14
-
There is no class for device 'PUSH_BUTTON_FLAT' yet
-

**Comment by coreGreenberet** [comment]
the class mapping for aio was missing
this will be fixed in #402

**Comment by oneteam2win** [comment]
thanks a lot
