### ISSUE TITLE
Update Auth Token for existing integration

### ISSUE THREAD

**Issue by LucTs** [coreGreenberet/homematicip-rest-api#393]
Hi,

I installed the HM IP integration via the Gui, not the manual way via configuration.yaml.
How can I update the Auth Token for the existing integration? Or can I simply delete the integration and add it again?

**Comment by coreGreenberet** [comment]
Are you talking about homeassistant? I'm just providing the api and not the integration itself.
@SukramJ can you answer that question?

**Comment by LucTs** [comment]
My bad. Yes, talking about Home Assistant. Should have posted that question in the HA repo.

@SukramJ Would be great if you can help.

**Comment by LucTs** [comment]
I simply deleted and added the integration vie the GUI
