### ISSUE TITLE
HmIP-ASIR trigger alarm

### ISSUE THREAD

**Issue by RP70DP** [coreGreenberet/homematicip-rest-api#396]
Is it possible to trigger an alarm for the functionalhome securityandhome or the device itself?

**Comment by coreGreenberet** [comment]
Sadly no =(

I've seen somewhere a workaround with HmIP-FCI1 & HmIP-PCBS.
The FCI1 was configured for security and connected to the PCBS. Then you just have to enable/disable the PCBS and the alarm would go on.

**Comment by RP70DP** [comment]
Thanks!
