### ISSUE TITLE
'ACCESS_CONTROL' isn't a valid option for class 'FunctionalHomeType'

### ISSUE THREAD

**Issue by FeromonDE** [coreGreenberet/homematicip-rest-api#398]
Logger: homematicip.base.enums
Source: /usr/local/lib/python3.8/site-packages/homematicip/base/enums.py:33
First occurred: 15:06:14 (11 occurrences)
Last logged: 15:18:15

'ACCESS_CONTROL' isn't a valid option for class 'FunctionalHomeType'

**Comment by LucTs** [comment]
```
Logger: homematicip.device
Source: /usr/local/lib/python3.8/site-packages/homematicip/device.py:140
First occurred: 07:42:14 (6 occurrences)
Last logged: 07:42:16

Optional Device Feature 'IFeatureProfilePeriodLimit' is not yet supported
```


I guess both errors are related to the new Homematic IP smart lock (HmIP-DLD)

**Comment by HansDampfwurst** [comment]
Do you need a dump file from homeassistant?

**Comment by Neisi** [comment]
> ```
> Logger: homematicip.device
> Source: /usr/local/lib/python3.8/site-packages/homematicip/device.py:140
> First occurred: 07:42:14 (6 occurrences)
> Last logged: 07:42:16
> 
> Optional Device Feature 'IFeatureProfilePeriodLimit' is not yet supported
> ```
> 
> I guess both errors are related to the new Homematic IP smart lock (HmIP-DLD)

Does someone have the new smart lock? 
Can someone create the dump-configuration file?
Would be great if the device were supported!
