### ISSUE TITLE
Error with new API-Version 8

### ISSUE THREAD

**Issue by CodeNightWriter** [coreGreenberet/homematicip-rest-api#4]
After generating a new auth token with VERSION 8 and calling list_devices.py I get the following error:
{
  "errorCode" : "CLIENT_VERSION_NOT_SUPPORTED"
}

Has anyone run this script successfully with the new Version?

**Comment by coreGreenberet** [comment]
Works fine for me since revision 6d8032a0090ee5bf8fa3b765fac5c9a4135530e3

**Comment by CodeNightWriter** [comment]
I've started completely new from scratch and now it works fine.
I couldn't find out what's wrong, but now I can start to extend the supported devices.
