### ISSUE TITLE
New Device

### ISSUE THREAD

**Issue by Sthreejay** [coreGreenberet/homematicip-rest-api#400]
In Home Assistant only the battery value of the device shows up but instead there should be 2 temperature values. thanks in advance for your help

https://de.elv.com/elv-homematic-ip-komplettbausatz-temperatursensor-mit-externen-fuehlern-2-fach-hmip-ste2-pcb-155614

[hmip-config_6084.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/6216566/hmip-config_6084.zip)

**Comment by coreGreenberet** [comment]
duplicate of #386
