### ISSUE TITLE
new device TEMPERATURE_SENSOR_2_EXTERNAL_DELTA

### ISSUE THREAD

**Issue by wettingus** [coreGreenberet/homematicip-rest-api#403]
It would be appreciated if you could implement
TEMPERATURE_SENSOR_2_EXTERNAL_DELTA

Thanks so much

[hmip-config_6110.zip](https://github.com/coreGreenberet/homematicip-rest-api/files/6266816/hmip-config_6110.zip)

**Comment by coreGreenberet** [comment]
this is already implemented in the api and got released in  [1.0.0](https://github.com/coreGreenberet/homematicip-rest-api/commit/c754d37f08adf9967f778d89f75d3e55bb01d115) 2 days ago.
