### ISSUE TITLE
Event Callbacks?

### ISSUE THREAD

**Issue by rekire** [coreGreenberet/homematicip-rest-api#407]
Sorry for this half off topic question I'm wondering if it is possible to be informed when a state or sensor has changed with this API.

To be honest I didn't check out your project yet. I was almost about to replace my silvercast bridge since I thought it has no APIs, but it seems that you even support that bridge. Really without limitations?

Can I create a callback **without polling** to get informed when some one is opening a door and there is movement or not to automate lamps e.g. with Philips Hue? (Last part of cause not with this SDK)

**Comment by steckenpferd** [comment]
Yes, Silvercrest HAP-B1 is supported

Yes, callback possible but be aware:
https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/206
