### ISSUE TITLE
New Statistics Support for HM IP devices

### ISSUE THREAD

**Issue by LucTs** [coreGreenberet/homematicip-rest-api#419]
Please add statistics support for below mentioned HMIP devices like describe here https://www.home-assistant.io/more-info/statistics/

HmIP-STHO-A
HmIP-BWTH

(Statistics available with new HA version 2021.8.0.)

**Comment by coreGreenberet** [comment]
Please Open an issue @homeassistant this library gets used by the integration, but it isn't the integration itself
