### ISSUE TITLE
Dependency constraints too loose

### ISSUE THREAD

**Issue by chrko** [coreGreenberet/homematicip-rest-api#423]
The specified dependencies version constraints in https://github.com/coreGreenberet/homematicip-rest-api/blob/master/setup.py and https://github.com/coreGreenberet/homematicip-rest-api/blob/master/requirements.txt are too loose and include also major releases which break some functionality, e.g. at least the websocket usage via `websocket-client` which changed the parameters of the callbacks.

Background: I'm just starting digging into the homematicIP product line and want to collect metrics with prometheus, looked at https://github.com/auhlig/homematicip-exporter but noticed that this just periodically polls instead using the events emitted via the websocket. Also I currently do not want to spend the effort setting up an own CCU, this seems the best approach to me.

j4i: I'm starting working on a pull request addressing this issue, but currently no (maybe not yet) interested in maintaining this project.

**Comment by cyraxx** [comment]
Adding this here so others can find it when they google the error message:

If you get errors such as `TypeError: _ws_on_message() takes 2 positional arguments but 3 were given` or `TypeError: _ws_on_error() takes 2 positional arguments but 3 were given` when running homematicip-rest-api, this is the reason. 

Until this is fixed, you'll need to explicitly install an older version of the websocket-client package. (Example: `pip3 install websocket-client==0.57.0`)

**Comment by coreGreenberet** [comment]
fixed in pr #437
