### ISSUE TITLE
HA 2021.12 -  loop keyword argument is deprecated

### ISSUE THREAD

**Issue by LucTs** [coreGreenberet/homematicip-rest-api#428]
Hi,

after updating to 2021.12 following notification can be found in the logs.
Can this be updated to prevent failing starting from version 2022.2?

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 08:58:55 (3 occurrences)
Last logged: 08:58:57

    Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue for homematicip_cloud using this method at homeassistant/components/homematicip_cloud/hap.py, line 254: await home.init(hapid)
    Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue for homematicip_cloud using this method at homeassistant/components/homematicip_cloud/hap.py, line 255: await home.get_current_state()
    Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue for homematicip_cloud using this method at homeassistant/components/homematicip_cloud/hap.py, line 188: await self.home.get_current_state()

**Comment by LucTs** [comment]
@coreGreenberet I know you are not actively working/developing the homematic IP rest API but would you mind look into this issue? I guess a lot of users using Home Assistant with Homematic IP would highly appreciate if the integration remains working with release 2022.2

Many thanks!

**Comment by mfrawley** [comment]
Fixed in https://github.com/coreGreenberet/homematicip-rest-api/pull/424 or?

**Comment by LucTs** [comment]
Hi @mfrawley,

yes looks like but I think a new release is required? See comment from Home Assistant colleagues: https://github.com/home-assistant/core/issues/65066#issuecomment-1025381208

**Comment by coreGreenberet** [comment]
I will push a new release this week. That should solve it.

**Comment by coreGreenberet** [comment]
released in https://github.com/coreGreenberet/homematicip-rest-api/commit/a60126747a36df6a1710dabaeb5ec1f84b682b66
