### ISSUE TITLE
Connection error with newest Version

### ISSUE THREAD

**Issue by gar00u** [coreGreenberet/homematicip-rest-api#50]
When using the newest API Version, I get an error on establishing the connection with error 403.

My host system is MacOS Version 10.13.

I recently installed python 3, Version 3.6.3

The required packages are installed in following Versions:
Name: requests, Version: 2.18.4
Name: websocket-client, Version: 0.44.0
Name: future, Version: 0.16.0

My config-file is the same I successfully used with the Python2 Version from 2 days ago. My Pi still runs the old Version (without Python3 changes and connection class) and works like a charm.

With activated debug I see the following Console output:
`2017-11-09 09:52:53,473 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): hmip1-1.homematic.com`
`2017-11-09 09:52:53,606 - urllib3.connectionpool - DEBUG - https://hmip1-1.homematic.com:6969 "POST /hmip/home/getCurrentState HTTP/1.1" 403 43`
`2017-11-09 09:52:53,610 - homematicip.connection - DEBUG - _restcall result: Errorcode=403 content({'errorCode': 'INVALID_AUTHORIZATION'})`
`2017-11-09 09:52:53,610 - homematicip.home - ERROR - Could not get the current configuration. Error: INVALID_AUTHORIZATION`

Do you have an idea what is going wrong?

**Comment by gar00u** [comment]
Additional info: Using my Pi with Python 3.4 gives me the same messages.

**Comment by coreGreenberet** [comment]
did you use the pip version or a clone of this repository?

**Comment by gar00u** [comment]
a clone of the repo.

**Comment by coreGreenberet** [comment]
It says invalid authorization. Try to recreate the access token

**Comment by gar00u** [comment]
I will try that later this evening.

the actual token still works using the old version.

**Comment by gar00u** [comment]
This didn't work out either. generate_auth_token.py gives me errors too.

>python3 generate_auth_token.py 
>Please enter the accesspoint id (SGTIN): ****-****-****-****-****-****
>Please enter the PIN (leave Blank if there is none): ****
>Please enter the client/devicename (leave blank to use default):
>Traceback (most recent call last):
>  File "generate_auth_token.py", line 19, in <module>
>    auth = homematicip.Auth()
>AttributeError: module 'homematicip' has no attribute 'Auth'

**Comment by coreGreenberet** [comment]
okay the generate_auth_token problem is fixed in e2f8d921e47dc6ee6afe60f0dfcf1af1d917fe25.
But I still have no Idea why your token isn't working in the new version :/
I'm still using the very first self generated token without any issues.

**Comment by gar00u** [comment]
Tried this out today. And it worked.
After generating a new token, and copying it from cmd i saw what the problem was.

The SGTIN in my old config file was formatted like this:
ACCESS_POINT = 'xxxx-xxxx-xxxx-xxxx-xxxx-xxxx'.

generate_auth_token.py shows me SGTIN without the "-".

After changing this in the config file the new version works.

**Comment by gar00u** [comment]
The old Version still supports SGTIN with "-". I think the code cropping the minusses from SGTIN is broken in the new Version.

**Comment by coreGreenberet** [comment]
Strange that should still work :/
I will change it to a regex replace to remove all "bad" characters.  This should fix the problem. (Maybe you had the "long minus" sign instead of the short/normal one.)

**Comment by gar00u** [comment]
See the comment in my merge request.

Haven't seen this the whole weekend...
