### ISSUE TITLE
Code line length

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#56]
Are we to adhere to PEP8 and keep the line length at a max of 79 characters ? My autoformatting keeps reformatting and suggesting commits ;-)

FYI:

https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by coreGreenberet** [comment]
actually I just wanted to "complain" about this in your last pull request...
I think pep8 is rather outdated with the line limit of 79 characters. At todays screens it isn't really necessary.

**Comment by sander76** [comment]
@coreGreenberet Other repo's I contribute to still adhere to the 79 line length pretty strictly. I prefer to do too. But you're the maintainer of this repo, so if you rather do not, I won't either. 

Must admit it is pretty worn into my programming style now, so there will still be some 79 line lengths. I'll do my best...
