### ISSUE TITLE
Move each device to a separate package ?

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#59]
With the amount of devices growing should we be putting each device in a separate package and put these in a separate devices module ?

**Comment by coreGreenberet** [comment]
Don't java it :p 
But we could do a device submodule and split them up by the base class

**Comment by sander76** [comment]
@coreGreenberet Never worked with Java, probably never will :-)

Assuming the file will keep growing I was thinking about it. On the other hand... How bad can it be?
