### ISSUE TITLE
implement get & update Profiles for heating groups

### ISSUE THREAD

**Issue by coreGreenberet** [coreGreenberet/homematicip-rest-api#6]

**Comment by coreGreenberet** [comment]
implemented in https://github.com/coreGreenberet/homematicip-rest-api/commit/5d7510f6cf8d8c25b3ea686cc25630e368dcddda

**Comment by phavel** [comment]
Current address: https://github.com/hahn-th/homematicip-rest-api/commit/5d7510f6cf8d8c25b3ea686cc25630e368dcddda
