### ISSUE TITLE
Add an "activate routing switch to the cli"

### ISSUE THREAD

**Issue by coreGreenberet** [coreGreenberet/homematicip-rest-api#68]
The cli needs a switch to de/activate the routing functionality on all devices which are supporting it

**Comment by sander76** [comment]
@coreGreenberet Just learning the hmip system. What do you mean by routing functionality ?

**Comment by coreGreenberet** [comment]
Some device are working as a repeater the for the radio signal, but this is disabled by default. This allows us to reach devices which aren't directly reachable by the ap.
The hmip labels this feature as routing.

**Comment by sander76** [comment]
@coreGreenberet ah. Clear!

**Comment by coreGreenberet** [comment]
Should be done with case #76
