### ISSUE TITLE
Move config file to json

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#69]
To move the `cli` tool inside the python package you should be able to refer to a config file located somewhere else on your computer.
It would make sense to:

- make config file a json file
- refer to the config file as a required argument when starting the `cli` tool

**Comment by coreGreenberet** [comment]
I was thinking about that too already. But not with json. More like a "normal" config file. 
I thought also about using default file locations if the parameter is empty
 Unix: /home/.. -> /etc/...
Windows: %appdata% -> %programdata% 
I did only a quick lookup if there is a library which does that, but I found only an older one which isn't maintained anymore

**Comment by sander76** [comment]
@coreGreenberet 
Doesn't really matter whether we use json/yaml/ini or anything.
For detecting home folder you could use:

https://docs.python.org/3/library/pathlib.html#pathlib.Path.home

**Comment by sander76** [comment]
@coreGreenberet btw. What do you mean by a "normal" config file ?

**Comment by coreGreenberet** [comment]
an editable file for "normal" people. similiar to the config.py or most linux config or ini files

**Comment by sander76** [comment]
@coreGreenberet 

How about this ?
https://docs.python.org/3/library/configparser.html

 No external dependencies required..

**Comment by sander76** [comment]
@coreGreenberet 

Have a look here:
https://github.com/sander76/homematicip-rest-api/blob/load_config_file/homematicip_cli.py

I started moving the config file to an ini file, but run into the issue of log setting. You seem to be doing that in two places. Can you have a look and let me know what you prefer ? After that I can finish it...

**Comment by coreGreenberet** [comment]
thanks! that looks already really nice.

for loading the config file location I would search for it on the drive. Something like this.
```python
import appdirs
from os import path
dirs = appdirs.AppDirs("HomeMaticIP", "coreGreenberet")
config_locations = [ args.config_file, "./config.ini", path.join(dirs.site_config_dir,"config.ini"), path.join(dirs.user_config_dir,"config.ini")]

for f in config_locations:
    try:
        if f is not None:
            _config = load_config_file(f)
            break
    except FileNotFoundError:
        pass
```

That way it will search for the file on the nearest location for the program. So if you are using more than one script with the same setting you won't have to specify the config file everytime.

1. The parameter you've specified
1. The current directory
1. The user config directory
1. The site config directory

For the logging:
I would do something similiar: If the parameter is specified -> use it. Otherwise use the one from the config file. (We have to remove the "default" value from argparse for that). If nothing is specified -> "30"

**Comment by coreGreenberet** [comment]
Which issue?

**Comment by sander76** [comment]
@coreGreenberet

No issue, but I guess we need to create this config handling so a new release can be put on pypi...

**Comment by coreGreenberet** [comment]
i've merged your changes in my local repository. I will try to publish a functional version tomorrow

**Comment by coreGreenberet** [comment]
this should be working now with fe060c7

**Comment by sander76** [comment]
@coreGreenBeret cool!
