### ISSUE TITLE
error when running generate_auth_token.py

### ISSUE THREAD

**Issue by bestgrafix** [coreGreenberet/homematicip-rest-api#77]
Hi i cant run the python script get the following error, could somebody help:

before i did: $ sudo pip install homematicip

 python ./generate_auth_token.py

Traceback (most recent call last):
  File "./generate_auth_token.py", line 2, in <module>
    import homematicip.auth
  File "/home/pi/homematicip-rest-api/homematicip/auth.py", line 14
    def __init__(self,home:Home):
                          ^
SyntaxError: invalid syntax

thanks in advanced

**Comment by sander76** [comment]
Don't use the pip version. Needs upgrading. Use the github repo. Good luck!

**Comment by kuzco1** [comment]
What do you exactly mean ?

I do get 
Traceback (most recent call last):
  File "./generate_auth_token.py", line 2, in <module>
    import homematicip.auth
  File "/home/cam/homematicip-rest-api/homematicip/auth.py", line 7, in <module>
    from homematicip.home import Home
  File "/home/cam/homematicip-rest-api/homematicip/home.py", line 12, in <module>
    import websocket
ImportError: No module named 'websocket'

**Comment by sander76** [comment]
This is not really homematic related but you could try and do the following:

```
# create a virtualenv
cd
python3 -m venv hmip
cd hmip
source bin/activate
# get this library from github.
git clone https://github.com/coreGreenberet/homematicip-rest-api.git
cd homematicip # enter the cloned folder
pip install -r requirements.txt # install requirements.
python setup.py install # install the actual library.
```

After this try and generate the auth token.

**Comment by kuzco1** [comment]
Many thanks. Working now.

**Comment by kuzco1** [comment]
Hello,
sorry, but I have to asked again (I am not a Linux guru).
I was able to "list may things", i.e. firmware, groups, etc..

After disconnecting my SSH session yesterday and reconnecting today; I have again an issue.
Going to hmip/homematicip-rest-api and running:
root@camserver:~/hmip/homematicip-rest-api# python ./homematicip_cli.py --list-firmware
Traceback (most recent call last):
  File "./homematicip_cli.py", line 12, in <module>
    from homematicip.home import Home
  File "/root/hmip/homematicip-rest-api/homematicip/home.py", line 12, in <module>
    import websocket
ImportError: No module named 'websocket'


Any hint is welcome.

**Comment by sander76** [comment]
@kuzco1 
do a `pip freeze` and see whether it says websocket somewhere (after you've activated the virtualenv)

**Comment by bestgrafix** [comment]
i found the problem, if you type python on raspbean it uses python2 but the script works only with python3 so  type python3 , things you need to know :)

and for installation
pip3 install homematicip
