### ISSUE TITLE
can not run: pip install homematicip

### ISSUE THREAD

**Issue by kuzco1** [coreGreenberet/homematicip-rest-api#79]
Hello, 
running debian 9, python 3.5.3 , python-pip 9.0.1-2, but when running:
pip install homematicip
I do get get:
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: No module named 'pip'

Any hint is welcome.

regards
kuzco1

**Comment by sander76** [comment]
See the other issue you've commented on. Problem you are describing here is not really hmip related.

**Comment by kuzco1** [comment]
Thanks for the hint.
With the description (please see other issue) I was able to install and run this solution.
