### ISSUE TITLE
catching individual button presses

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#80]
I have a HMIP-WRC2 device. I am trying to catch individual key presses of this device, but I am only getting a "DEVICE CHANGED" event which does not say which of two buttons are actually pressed.

Anyone any idea how to catch individual key presses of this device (did the same with the 8 button remote control without succes).

**Comment by coreGreenberet** [comment]
I don't have the WRC2 device (or something similiar). Can you try to look at the json with the cli with the --dump-configuration parameter? Can you see if the buttons are pressed or not?

**Comment by sander76** [comment]
See below for the output (id's are fake). Always the "complete" device is reported. It shows nowhere which button is pressed. I'm starting to think it is not possible...

"""
{
    "id": "A0004F71193C99517FF30011",
    "homeId": "fake",
    "label": "Wall-mount Remote Control",
    "lastStatusUpdate": 1512478146235,
    "type": "PUSH_BUTTON",
    "functionalChannels": {
        "0": {
            "label": "",
            "deviceId": "A0004F71193C99517FF30011",
            "index": 0,
            "groupIndex": 0,
            "functionalChannelType": "DEVICE_BASE",
            "groups": [
                "8ba14126-6403-4f75-9c0f-1950e7d7563a"
            ],
            "unreach": false,
            "lowBat": false,
            "routerModuleEnabled": false,
            "routerModuleSupported": false,
            "rssiDeviceValue": -76,
            "rssiPeerValue": null
        },
        "1": {
            "label": "",
            "deviceId": "A0004F71193C99517FF30011",
            "index": 1,
            "groupIndex": 1,
            "functionalChannelType": "SINGLE_KEY_CHANNEL",
            "groups": [
                "f5218c3d-05e4-4260-9c37-c336d882967e"
            ]
        },
        "2": {
            "label": "",
            "deviceId": "A0004F71193C99517FF30011",
            "index": 2,
            "groupIndex": 1,
            "functionalChannelType": "SINGLE_KEY_CHANNEL",
            "groups": [
                "f5218c3d-05e4-4260-9c37-c336d882967e"
            ]
        }
    },
    "oem": "eQ-3",
    "manufacturerCode": 1,
    "updateState": "UP_TO_DATE",
    "firmwareVersion": "1.4.2",
    "availableFirmwareVersion": "0.0.0",
    "serializedGlobalTradeItemNumber": "A0004F71193C99517FF30011",
    "modelType": "HMIP-WRC2",
    "modelId": 261,
    "api_name": "AsyncPushButton"
}
"""

**Comment by coreGreenberet** [comment]
I've also looked more into the HMIP App. There isn't any information in the object or calls to the rest api which makes it clearer which button is pressed.

The only option I can see at the moment is to use the key to change a PS/PSM/... and handle the event from there :/
