### ISSUE TITLE
control the heating element temperature ?

### ISSUE THREAD

**Issue by bestgrafix** [coreGreenberet/homematicip-rest-api#81]
Hi short questions is it possible to control the heating element temperature ?

My Homeatic IP Device
Homematic IP Heizkörperthermostat HMIP-eTRV/2 140280

tried
 python3 homematicip_cli.py --device ID  --set-display setpoint 20

but didnt worked, is it even possible ?

**Comment by coreGreenberet** [comment]
--set-display setpoint will just change what should be displayed on the display of the HmIP-WTH/HmIP-WTH-2 which might be the current temperature, the temperature which it is configured or the current temperature & humidity

currently there is no option in the cli to set the room temperature. I will add this to the cli in the near future.

There is however a difference to your usage. The room temperature is based on a group and not on the device.

so the syntax will be something like 
python3 homematicip_cli.py --group ID --set-point-temperature 20

**Comment by bestgrafix** [comment]
Thx for the info, but didnt worked :)
--list-groups gives me only something like
HEATING Arbeitszimmer windowOpenTemperature(10.0) setPointTemperature(23.0) windowState(CLOSED) motionDetected(30.0) sabotage(5.0) cooling(None) partyMode(False) controlMode(AUTOMATIC) actualTemperature(21.9)

python3 homematicip_cli.py --group Arbeitszimmer --set-point-temperature 20 gives me only a syntax error, tried different combinatations with HEATING Arbeitszimmer oder META Arbeitszimmer, but didnt worked.

**Comment by coreGreenberet** [comment]
read my post again:
"currently there is no option in the cli to set the room temperature. I will add this to the cli in the near future."
it should work like in your last line as soon as it is implemented

**Comment by bestgrafix** [comment]
Ah ok i thought there where another possibility , looking forward to it :)

Using it already for Openhab2 , thanks for that script 👍

**Comment by coreGreenberet** [comment]
try it now =)

**Comment by bestgrafix** [comment]
Yes it worked, awesome, now i can build the complete heating control in openhab2 / pimatic :)
