### ISSUE TITLE
Add class for ROOM_CONTROL_DEVICE

### ISSUE THREAD

**Issue by phanlipo** [coreGreenberet/homematicip-rest-api#85]
I've added [this](https://www.wesmartify.de/shop/heizungssysteme/heizkoerperradiator/17/raumbediengeraet-display?c=44) room control device.

Afterwards I get the error

`There is no class for ROOM_CONTROL_DEVICE yet`

Can you implement this device?

Thank you in advance!

**Comment by coreGreenberet** [comment]
could you please run' ./homematicip_cli.py --dump-configuration' and post the result here?

**Comment by phanlipo** [comment]
Yes, of course. I've changed only some personal data. If there is more information necessary, please do not hesitate to ask me.

[GitHub.log](https://github.com/coreGreenberet/homematicip-rest-api/files/1788835/GitHub.log)

**Comment by sander76** [comment]
Seems like it is not a "standard" home matic device is it ?

**Comment by phanlipo** [comment]
You mean because of the brand "wesmartify"? I think Möhlenhoff is the OEM behind these Smart Home devices and uses the Homematic IP standard from eQ-3. 

[See also](https://www.moehlenhoff.de/index.php?option=com_content&view=article&id=150:eq3-moehlenhoff&catid=16:news&Itemid=36&lang=en)

**Comment by coreGreenberet** [comment]
should be working now. can you try it with the latest version from github?

**Comment by phanlipo** [comment]
Yes, it works now. 

```
user@computer:~/$ python3 homematic_cli.py --list-devices
3014F611C8000A178858E5BF HmIP-eTRV-2 Heizkörperthermostat lowbat(False) unreach(False) rssiDeviceValue(-44) rssiPeerValue(-42): operationLockActive(False) valvePosition(None) valveState(WAIT_FOR_ADAPTION)

3014F611C80001D5E858A4CA HMIP-PSM Waschmaschine lowbat(None) unreach(False) rssiDeviceValue(-41) rssiPeerValue(-72): on(True) profileMode(None) userDesiredProfileMode(AUTOMATIC) energyCounter(2.5309) currentPowerConsumption(0.05W)

3014F611C80006D788585FFF ALPHA-IP-RBG Raumbediengerät lowbat(None) unreach(None) rssiDeviceValue(0) rssiPeerValue(0): actualTemperature(23.0) humidity(35) setPointTemperature(21.0)

3014F611C8000E578858B70D HmIP-STH Temperatur- und Luftfeuchtigkeitssensor lowbat(False) unreach(False) rssiDeviceValue(-63) rssiPeerValue(-63): actualTemperature(20.8) humidity(44)
```

P.S.: I was a bit confused of some DEBUG messages of urllib3, but it is connected with the default Logging Level of 10 (DEBUG). https://docs.python.org/2/library/logging.html#logging-levels
