### ISSUE TITLE
Home-Assistant support

### ISSUE THREAD

**Issue by mxworm** [coreGreenberet/homematicip-rest-api#86]
Hi,

I started to add support for HomematicIP to HomeAssistant based on your library.
https://github.com/home-assistant/home-assistant/pull/12761
I plan to add support for a few more devices which I own in the next days.
Are you going to release a new version of all the changes and new devices you have added soon?

Ciao Mattias

**Comment by sander76** [comment]
Hi Mattias,

I just posted a comment on your pull request.
Can you have a look?

https://github.com/home-assistant/home-assistant/pull/12761

**Comment by coreGreenberet** [comment]
Actually yes.  I want to add the scripts to the pip setup. As soon as this is working I will create a new tag

**Comment by coreGreenberet** [comment]
try it 0.9 is out =)
