### ISSUE TITLE
Testcases

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#95]
Read your request and I thought to make an issue out of it. Good place to discuss this I guess.

**Comment by coreGreenberet** [comment]
That might work too^^

**Comment by sander76** [comment]
Right now my test server is a bit messy. And can use some cleanup, so digging through it can be hard I guess. 
The other thing is my testserver is async. The benefit here is that it fairly easy to setup for testing. See the discussion here:

https://stackoverflow.com/questions/47224765/pytest-testing-of-a-websocket-connection

So if you'd want to use it for your cases you'd need a threaded version of my server.

For the websocket testing I think of restructuring it and setting up another server with which I can test server errors, disconnects etc.
With other tests I am thinking of mocking out the api calls and on that.

**Comment by coreGreenberet** [comment]
Does it really matter if the server itself is threaded it not? Even when it is on localhost the session goes over tcp. The client doesn't know the "backend" of the server, so it shouldn't really matter. 

The FakeResolver must be implemented differently here for the requests I guess.

**Comment by coreGreenberet** [comment]
That makes sense =D
Sounds like a Plan^^

**Comment by coreGreenberet** [comment]
@sander76 
I've started with the implementation via a WSGI Server which runs on a different thread
Could you try to use it the async implementation?

**Comment by sander76** [comment]
@coreGreenberet 
I will. But currently I lack time working on it unfortunately..

**Comment by coreGreenberet** [comment]
No worries:) I'm thankful for any help.

**Comment by coreGreenberet** [comment]
I've created a new branch.
https://github.com/coreGreenberet/homematicip-rest-api/tree/async_test_cases

the async_home_fixture will use the same webserver in the background as the single threaded version, but the fixture isn't working at the moment. It won't update the lookup_url correctly

**Comment by coreGreenberet** [comment]
@sander76 @mxworm 
could you please help me with https://github.com/coreGreenberet/homematicip-rest-api/blob/master/tests/aio_tests/test_async_auth.py

These tests are always failing and I don't really get why. The "request" version is working fine.

**Comment by mxworm** [comment]
Hi, I think connectionRequest gives you only a status e.g. throwes exception and has no real return value.

**Comment by sander76** [comment]
Not sure. Does the async version even work ?
I mean, I see an init method implement not present in the non-sync version.

**Comment by mxworm** [comment]
Hi, yes async auth is working. I use it for the "Integrations flow" in homeassistent, now users can directly generate there authtoken in the GUI :-)
https://github.com/home-assistant/home-assistant/pull/14861

**Comment by sander76** [comment]
@coreGreenberet @mxworm To be honest: I don't know where to start solving this. I have major issues with even trying to start these tests. They all exit with path errors etc etc.
One thing I'd like to discuss is whether "rebuilding" a cloud server for testing purposes is the way to go?
If Eq3 decides to change stuff you need to redesign the complete server.
I feel we should mock out responses and act on those.

**Comment by coreGreenberet** [comment]
thats strange :/ maybe you could look it up how I'm doing the test cases with circleci? if you are using the same commands it should work.

Well I would like to stick with the Fake Server. The reason is that you can't fully test all cases (e.g. all the "set" functions) via Mock. 
If Eq3 tries to change the API, than we would have to change it in all classes too. With a "complete" server it will be easier to test the API.

**Comment by sander76** [comment]
@coreGreenberet I always struggle what and how to test and what not. I guess it is more a matter of preference.
But the amount of work you have put into making a fake server is impressive! Still I am a bit in doubt whether this is the best way to go and if I google on "testing external API's" you always run into mocking out requests... (Need to add though that my testing skills are only just average I'd say..)
